cosmos-installer: null
name: big-bear-ghostfolio
services:
  "{ServiceName}-big-bear-ghostfolio":
    container_name: "{ServiceName}-big-bear-ghostfolio"
    image: ghostfolio/ghostfolio:2.139.1
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: "3333"
      ACCESS_TOKEN_SALT: 5a7f9e0d-0e64-4c19-8279-bbe8b4c590f4
      DATABASE_URL: postgresql://ghostfolio:casaospassword@{ServiceName}-big-bear-ghostfolio-db:5432/ghostfolio?sslmode=prefer
      JWT_SECRET_KEY: 534e820d-da30-4dd3-baf9-0511847c478a
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: casaospassword
      REDIS_HOST: "{ServiceName}-big-bear-ghostfolio-redis"
      REDIS_PASSWORD: casaosredispassword
      REDIS_PORT: "6379"
    ports:
      - 3333:3333
    depends_on:
      - "{ServiceName}-big-bear-ghostfolio-db"
      - "{ServiceName}-big-bear-ghostfolio-redis"
    networks:
      - big_bear_ghostfolio_network
    hostname: "{ServiceName}-big-bear-ghostfolio"
  "{ServiceName}-big-bear-ghostfolio-db":
    container_name: "{ServiceName}-big-bear-ghostfolio-db"
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: casaospassword
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d ghostfolio -U ghostfolio
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "{ServiceName}-big-bear-ghostfolio-db-data:/var/lib/postgresql/data"
    networks:
      - big_bear_ghostfolio_network
    hostname: "{ServiceName}-big-bear-ghostfolio-db"
  "{ServiceName}-big-bear-ghostfolio-redis":
    container_name: "{ServiceName}-big-bear-ghostfolio-redis"
    image: redis:7-alpine
    restart: unless-stopped
    command: |
      --requirepass casaosredispassword
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - "{ServiceName}-big-bear-ghostfolio-redis-data:/data"
    networks:
      - big_bear_ghostfolio_network
    hostname: "{ServiceName}-big-bear-ghostfolio-redis"
networks:
  big_bear_ghostfolio_network:
    driver: bridge
minVersion: 0.14.0
