cosmos-installer: null
name: big-bear-vikunja
services:
  "{ServiceName}-vikunja":
    image: vikunja/vikunja:0.24.6
    container_name: "{ServiceName}-vikunja"
    ports:
      - 8081:3456
    volumes:
      - "{ServiceName}-vikunja-data:/app/vikunja/files"
    environment:
      VIKUNJA_SERVICE_PUBLICURL: http://<your public frontend url with slash>/
      VIKUNJA_DATABASE_HOST: vikunja-db
      VIKUNJA_DATABASE_PASSWORD: secret
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: 4c2ad520-f177-425f-ab7f-64c5e2b1c2c8
    restart: unless-stopped
    depends_on:
      - "{ServiceName}-vikunja-db"
    networks:
      - vikunja-network
    hostname: "{ServiceName}-vikunja"
  "{ServiceName}-vikunja-db":
    image: mariadb:10
    container_name: "{ServiceName}-vikunja-db"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: vikunja
    volumes:
      - "{ServiceName}-vikunja-db-data:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - vikunja-network
    hostname: "{ServiceName}-vikunja-db"
networks:
  vikunja-network:
    driver: bridge
minVersion: 0.14.0
