cosmos-installer: null
name: big-bear-immich-aio-alpine
services:
  "{ServiceName}-big-bear-immich-aio-alpine":
    container_name: "{ServiceName}-big-bear-immich-aio-alpine"
    image: ghcr.io/imagegenius/immich:1.125.3-alpine
    ports:
      - 2283:8080
    volumes:
      - "{ServiceName}-big-bear-immich-aio-alpine-data:/config"
      - "{ServiceName}-big-bear-immich-aio-alpine-data-2:/usr/src/app/photos"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=big-bear-immich-db
      - DB_USERNAME=casaos
      - DB_PASSWORD=casaos
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=big-bear-immich-redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MACHINE_LEARNING_GPU_ACCELERATION=
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120
    depends_on:
      - "{ServiceName}-big-bear-immich-redis"
      - "{ServiceName}-big-bear-immich-db"
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-big-bear-immich-aio-alpine"
  "{ServiceName}-big-bear-immich-redis":
    container_name: "{ServiceName}-big-bear-immich-redis"
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-big-bear-immich-redis"
  "{ServiceName}-big-bear-immich-db":
    container_name: "{ServiceName}-big-bear-immich-db"
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - "{ServiceName}-big-bear-immich-db-data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-big-bear-immich-db"
networks:
  big_bear_immich_network:
    driver: bridge
minVersion: 0.14.0
