cosmos-installer: null
services:
  app:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
      - target: 9001
        published: 48114
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /mosquitto/config
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /mosquitto/data
      - type: bind
        source: /DATA/AppData/$AppID/log
        target: /mosquitto/log
minVersion: 0.14.0
