cosmos-installer: null
name: big-bear-scrutiny
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/opt/scrutiny/config"
      - "{ServiceName}-data-2:/opt/scrutiny/influxdb"
      - /run/udev:/run/udev:ro
    ports:
      - 38080:8080
      - 38086:8086
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0:/dev/nvme0
    privileged: true
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/api/health
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    hostname: "{ServiceName}"
minVersion: 0.14.0
