cosmos-installer: null
services:
  app:
    image: linuxserver/mysql-workbench:8.0.47@sha256:280372c734cb9fc0ce5eeebff04fb70f7374ed69b1e580b3b3eab6242520be18
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mysql-workbench/config
        target: /config
minVersion: 0.14.0
