cosmos-installer: null
name: big-bear-wg-easy
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/wg-easy/wg-easy:14
    restart: unless-stopped
    environment:
      WG_HOST: "[YOUR_PUBLIC_IP]"
      PASSWORD_HASH: $2b$12$coPqCsPtcFO.Ab99xylBNOW4.Iu7OOA2/ZIboHN6/oyxca3MWo7fW
      WG_DEFAULT_DNS: 1.1.1.1
      WG_ALLOWED_IPS: 0.0.0.0/0, ::/0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - "{ServiceName}-data:/etc/wireguard"
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    hostname: "{ServiceName}"
minVersion: 0.14.0
