cosmos-installer: null
name: big-bear-homepage
services:
  "{ServiceName}":
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: "{ServiceName}"
    ports:
      - 3000:3000
    volumes:
      - "{ServiceName}-data:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: "{ServiceName}"
minVersion: 0.14.0
