cosmos-installer: null
services:
  app:
    image: linuxserver/lollypop:1.4.45@sha256:2237b0a1e9a81009b5f1b8838781b77c1fce172e6d71a0db2a9a215c64e2b755
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lollypop/config
        target: /config
minVersion: 0.14.0
