cosmos-installer: null
services:
  app:
    image: linuxserver/lollypop:1.4.45@sha256:f80b5737059d5a2b7e9ed12e507eff4eceda4d6174b0ffd009faf5d7ead60bd3
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lollypop/config
        target: /config
minVersion: 0.14.0
