cosmos-installer: null
services:
  app:
    image: linuxserver/ldap-auth:3.4.8@sha256:8939d638970d72a10979e7b1635715fc0ee8ed8cc8ed50b2e0d1c613208f7756
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
minVersion: 0.14.0
