cosmos-installer: null
services:
  app:
    image: linuxserver/ldap-auth:3.4.8@sha256:9b94624ff3dff4bcf6d7ba74a9186afe6ac334e48104bb5f688ddf6866659957
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
minVersion: 0.14.0
