cosmos-installer: null
services:
  app:
    image: linuxserver/ldap-auth:3.4.8@sha256:4f404fd3b0236e4a3c47a137a6f34d74094cde51471bce66d921f50289b6bf46
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FERNETKEY: ''
      CERTFILE: ''
      KEYFILE: ''
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 9000
        published: 9000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ldap-auth/config
        target: /config
minVersion: 0.14.0
