cosmos-installer: null
name: big-bear-python-matter-server
services:
  "{ServiceName}":
    image: ghcr.io/home-assistant-libs/python-matter-server:6.1.2
    container_name: "{ServiceName}"
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor:unconfined
    volumes:
      - "{ServiceName}-data:/data/"
      - /run/dbus:/run/dbus:ro
    hostname: "{ServiceName}"
minVersion: 0.14.0
