# Configuration for pwpush setup

# Name of the big-bear-pwpush application
name: big-bear-pwpush
# Service definitions for the big-bear-pwpush application
services:
  # Service name: big-bear-pwpush
  # The `big-bear-pwpush` service definition
  big-bear-pwpush:
    # Name of the container (Docker does not have to generate a random name)
    container_name: big-bear-pwpush
    # Image to be used for the container
    image: pglombardo/pwpush:1.62.1
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      # Database connection string
      DATABASE_URL: "mysql2://pwpusher:6280144a-56af-486f-9088-ac7301399328@big-bear-pwpush-db:3306/passwordpusher_db"
      # Password expiration settings
      PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: "1"
      PWP__PW__EXPIRE_AFTER_VIEWS_MIN: "1"
      PWP__PW__RETRIEVAL_STEP_DEFAULT: "true"
    # Volumes to be mounted to the container
    volumes:
      # Storage volume
      - passwordpusher_storage:/opt/PasswordPusher/storage
    # Ports mapping between host and container
    ports:
      # Mapping port 5100 of the host to port 5100 of the container
      - "5100:5100"
    networks:
      - big_bear_pwpush_network
  big-bear-pwpush-db:
    container_name: big-bear-pwpush-db
    image: mariadb:10.6.5
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: "pwpusher"
      MARIADB_PASSWORD: "6280144a-56af-486f-9088-ac7301399328"
      MARIADB_DATABASE: "passwordpusher_db"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - passwordpusher_mysql:/var/lib/mysql
    networks:
      - big_bear_pwpush_network
networks:
  big_bear_pwpush_network:
    driver: bridge
volumes:
  passwordpusher_storage: {}
  passwordpusher_mysql: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: passwordpusher
    description: Password Pusher
    useHost: true
    target: http://localhost:5100
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
