# Configuration for cloudflared-web setup

# Name of the big-bear-cloudflared-web application
name: big-bear-cloudflared-web
# Service definitions for the big-bear-cloudflared-web application
services:
  # Service name: big-bear-cloudflared-web
  # The `big-bear-cloudflared-web` service definition
  big-bear-cloudflared-web:
    # Name of the container
    container_name: big-bear-cloudflared-web
    # Image to be used for the container
    image: wisdomsky/cloudflared-web:2025.10.0
    # Container restart policy
    restart: unless-stopped
    # Network mode
    network_mode: host
    # Environment variables for the container
    environment:
      - WEBUI_PORT=14333
      - EDGE_IP_VERSION=auto
      - PROTOCOL=auto
      - METRICS_ENABLE=false
      - METRICS_PORT=60123
      - BASIC_AUTH_USER=admin
      - BASIC_AUTH_PASS=""

# Cosmos-specific routes for reverse proxy
routes:
  - name: cloudflared-web
    description: Cloudflared Web
    useHost: true
    target: http://localhost:14333
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
