cosmos-installer: null
services:
  app:
    image: linuxserver/pcsx2:2.8.2@sha256:cf33a35769e299772ec213b595c3113cc10416ad67da10ef9f2275c32a3bd83d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pcsx2/config
        target: /config
minVersion: 0.14.0
