cosmos-installer: null
services:
  app:
    image: linuxserver/pcsx2:2.8.2@sha256:4e7e61591f06b4f7ba94065888e70093f99b04644b0460baaa262ef896f2077c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pcsx2/config
        target: /config
minVersion: 0.14.0
