cosmos-installer: null
name: big-bear-open-webui
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/open-webui/open-webui:git-90503be
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/app/backend/data"
    environment:
      - OLLAMA_BASE_URL=
      - OPENAI_API_KEY=
    ports:
      - 8080:8080
    hostname: "{ServiceName}"
minVersion: 0.14.0
