cosmos-installer: null
services:
  app:
    image: linuxserver/manyfold:0.150.0@sha256:57193ffbbf8968af410f6fffe95f43de66977324066103a988a0568910ff3eb7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DATABASE_URL: ''
      REDIS_URL: ''
      SECRET_KEY_BASE: ''
    ports:
      - target: 3214
        published: 3214
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/manyfold/config
        target: /config
      - type: bind
        source: /DATA/AppData/manyfold/libraries
        target: /libraries
minVersion: 0.14.0
