cosmos-installer: null
name: big-bear-glances
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: nicolargo/glances:4.3.0.8-full
    ports:
      - 61208:61208
    environment:
      - TZ=UTC
      - GLANCES_OPT=-w
    pid: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    hostname: "{ServiceName}"
minVersion: 0.14.0
