cosmos-installer: null
name: big-bear-monica
services:
  "{ServiceName}-big-bear-monica":
    container_name: "{ServiceName}-big-bear-monica"
    image: monica:4.1.2
    restart: unless-stopped
    environment:
      - APP_KEY=80356f7073c4f7834187b25a9d32cd2a
      - DB_HOST={ServiceName}-big-bear-monica-db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=passwordmonica
    volumes:
      - "{ServiceName}-big-bear-monica-data:/var/www/html/storage"
    ports:
      - 8080:80
    networks:
      - big_bear_monica_network
    hostname: "{ServiceName}-big-bear-monica"
  "{ServiceName}-big-bear-monica-db":
    image: mariadb:10.6.11
    container_name: "{ServiceName}-big-bear-monica-db"
    environment:
      - TZ=UTC
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=monica
      - MARIADB_USER=usermonica
      - MARIADB_PASSWORD=passwordmonica
    volumes:
      - "{ServiceName}-big-bear-monica-db-data:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - big_bear_monica_network
    hostname: "{ServiceName}-big-bear-monica-db"
networks:
  big_bear_monica_network:
    driver: bridge
minVersion: 0.14.0
