cosmos-installer: null
name: big-bear-octoprint
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: octoprint/octoprint:1.11.2
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/octoprint"
    ports:
      - 1080:80
    hostname: "{ServiceName}"
minVersion: 0.14.0
