cosmos-installer: null
name: big-bear-octoprint
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: octoprint/octoprint:1.9.3
    restart: unless-stopped
    volumes:
      - "{DefaultDataPath}/AppData/{ServiceName}/octoprint:/octoprint"
    ports:
      - 1080:80
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
