cosmos-installer: null
services:
  app:
    image: linuxserver/yaak:2026.8.1@sha256:03ee7b148139da77eaa2c2d29db2d15025c2f8e62331d7c2d8f02df1838a9381
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yaak/config
        target: /config
minVersion: 0.14.0
