cosmos-installer: null
name: big-bear-romm
services:
  "{ServiceName}-big-bear-romm":
    image: rommapp/romm:3.7.0
    container_name: "{ServiceName}-big-bear-romm"
    environment:
      - DB_HOST={ServiceName}-big-bear-rommdb
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_NAME=romm
      - DB_PASSWD=casaos
      - ROMM_AUTH_SECRET_KEY=<secret key>
      - IGDB_CLIENT_ID=<igdb client id>
      - IGDB_CLIENT_SECRET=<igdb client secret>
      - MOBYGAMES_API_KEY=<moby api key>
      - STEAMGRIDDB_API_KEY=<sgdb api key>
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true
      - ENABLE_SCHEDULED_RESCAN=true
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true
    volumes:
      - "{ServiceName}-big-bear-romm-data:/romm/resources"
      - "{ServiceName}-big-bear-romm-data-2:/redis-data"
      - "{ServiceName}-big-bear-romm-data-3:/romm/library"
      - "{ServiceName}-big-bear-romm-data-4:/romm/assets"
      - "{ServiceName}-big-bear-romm-data-5:/romm/config"
      - "{ServiceName}-big-bear-romm-data-6:/romm/logs"
    ports:
      - 1080:8080
    depends_on:
      - "{ServiceName}-big-bear-rommdb"
    restart: unless-stopped
    networks:
      - big-bear-romm-network
    hostname: "{ServiceName}-big-bear-romm"
  "{ServiceName}-big-bear-rommdb":
    image: mariadb:latest
    container_name: "{ServiceName}-big-bear-rommdb"
    environment:
      - MYSQL_ROOT_PASSWORD=casaos
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=casaos
    volumes:
      - "{ServiceName}-big-bear-rommdb-data:/var/lib/mysql"
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - big-bear-romm-network
    hostname: "{ServiceName}-big-bear-rommdb"
networks:
  big-bear-romm-network:
    driver: bridge
minVersion: 0.14.0
