cosmos-installer: null
services:
  app:
    image: linuxserver/dokuwiki:version-2026-07-14c@sha256:c2d3125e994e9d508f39af4ee04caf4ee07a47149305974d3275febd3b81a45d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dokuwiki/config
        target: /config
minVersion: 0.14.0
