cosmos-installer: null
services:
  app:
    image: linuxserver/limnoria:2026.5.8@sha256:d3de58e50fda7a70ee6b3521299e415f609260370ca09f5f083681239917944e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
minVersion: 0.14.0
