cosmos-installer: null
services:
  app:
    image: linuxserver/limnoria:2026.5.8@sha256:ccbc27f692643d1c79a362262c2ed0c47d870e2a7cd206028b83e19f4c2ca050
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/limnoria/config
        target: /config
minVersion: 0.14.0
