cosmos-installer: null
services:
  app:
    image: linuxserver/openshot:4.0.0@sha256:64c44b097911fd11cd95d61653a9d3b87d1f679449afdf2e7954949a83bcb2dc
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/openshot/config
        target: /config
minVersion: 0.14.0
