# Configuration for npmplus setup

# Name of the big-bear-npmplus application
name: big-bear-npmplus
# Service definitions for the big-bear-npmplus application
services:
  # Service name: big-bear-npmplus
  # The `big-bear-npmplus` service definition
  big-bear-npmplus:
    # Name of the container
    container_name: big-bear-npmplus
    # Image to be used for the container
    image: zoeyvid/npmplus:449
    # Container restart policy
    restart: unless-stopped
    # Network mode for the container
    network_mode: host
    environment:
      - "TZ=America/Chicago" # Required for the container to function properly
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/data directory to /data inside the container
      - "npmplus_data:/data"
volumes:
  npmplus_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: npmplus
    description: NPMPlus
    useHost: true
    target: http://localhost:81
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
