cosmos-installer: null
name: big-bear-komf
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: sndxr/komf:1.2.1
    restart: unless-stopped
    environment:
      - KOMF_KOMGA_BASE_URI=http://komga:25600
      - KOMF_KOMGA_USER=admin@example.org
      - KOMF_KOMGA_PASSWORD=admin
      - KOMF_KAVITA_BASE_URI=http://kavita:5000
      - KOMF_KAVITA_API_KEY=cd1edcc1-6010-41a8-a82b-73f501dc2760
      - KOMF_LOG_LEVEL=INFO
    volumes:
      - "{ServiceName}-data:/config"
    user: 1000:1000
    ports:
      - 8085:8085
    networks:
      - big_bear_komf_network
    hostname: "{ServiceName}"
networks:
  big_bear_komf_network:
    driver: bridge
minVersion: 0.14.0
