# Configuration for komga setup

# Name of the big-bear-komga application
name: big-bear-komga
# Service definitions for the big-bear-komga application
services:
  # Service name: big-bear-komga
  # The `big-bear-komga` service definition
  big-bear-komga:
    # Name of the container
    container_name: big-bear-komga
    # Image to be used for the container
    image: ghcr.io/gotson/komga:1.23.5
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      - TZ=UTC
    # Volumes to be mounted to the container
    volumes:
      - komga_config:/config
      - komga_data:/data
    # Ports mapping between host and container
    ports:
      # Mapping port 25600 of the host to port 25600 of the container
      - "25600:25600"
volumes:
  komga_config: {}
  komga_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: komga
    description: Komga
    useHost: true
    target: http://localhost:25600
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
