cosmos-installer: null
name: big-bear-traccar
services:
  "{ServiceName}":
    image: traccar/traccar:6.4-ubuntu
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
    restart: unless-stopped
    ports:
      - 8080:8082
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
    volumes:
      - "{ServiceName}-data:/opt/traccar/logs"
      - "{ServiceName}-data-2:/opt/traccar/conf/traccar.xml"
minVersion: 0.14.0
