cosmos-installer: null
name: big-bear-unifi-network-application
services:
  "{ServiceName}-unifi-db":
    image: mongo:6.0.11
    container_name: "{ServiceName}-unifi-db"
    volumes:
      - "{ServiceName}-unifi-db-data:/data/db"
      - "{ServiceName}-unifi-db-data-2:/docker-entrypoint-initdb.d/init-mongo.js"
    ports:
      - 27017:27017
    networks:
      - unifi-nework-application-network
    restart: unless-stopped
    hostname: "{ServiceName}-unifi-db"
  "{ServiceName}-app":
    image: linuxserver/unifi-network-application:8.6.9
    container_name: "{ServiceName}-app"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_HOST={ServiceName}-{ServiceName}-big-bear-unifi-db
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_password
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      - MONGO_TLS=
      - MONGO_AUTHSOURCE=
    volumes:
      - "{ServiceName}-app-data:/config"
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    restart: unless-stopped
    networks:
      - unifi-nework-application-network
    depends_on:
      - "{ServiceName}-unifi-db"
    hostname: "{ServiceName}-app"
networks:
  unifi-nework-application-network:
    driver: bridge
minVersion: 0.14.0
