# Configuration for big-bear-otel-lgtm setup

# Name of the big-bear-otel-lgtm application
name: big-bear-otel-lgtm
# Service definitions for big-bear-otel-lgtm application
services:
  # Service name: big-bear-otel-lgtm
  # The `big-bear-otel-lgtm` service definition
  big-bear-otel-lgtm:
    # Name of the container
    container_name: big-bear-otel-lgtm
    # Image to be used for the container
    image: grafana/otel-lgtm:0.11.12
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/data directory to /data inside the container
      - |-
        otel_lgtm_
        type
        source
        target
        bind
          create_host_path:
         bind
         /DATA/AppData/$AppID/data
         /data

         true
    # Ports mapping between host and container
    ports:
      # Mapping port 3000 of the host to port 3000 of the container
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
      # Mapping port 4317 of the host to port 4317 of the container  
      - mode: ingress
        target: 4317
        published: "4317"
        protocol: tcp
      # Mapping port 4318 of the host to port 4318 of the container  
      - mode: ingress
        target: 4318
        published: "4318"
        protocol: tcp
    # Networks to be attached to the container
    networks:
      - big-bear-otel-lgtm
networks:
  big-bear-otel-lgtm:
    driver: bridge

# Cosmos-specific routes for reverse proxy
routes:
  - name: otel-lgtm
    description: OTEL LGTM
    useHost: true
    target: http://localhost:3000
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
