cosmos-installer: null
name: big-bear-casaos-user-management
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: bigbeartechworld/big-bear-casaos-user-management:0.1.0
    restart: unless-stopped
    privileged: true
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - ADMIN_USERNAME=casaos
      - ADMIN_PASSWORD=casaos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/casaos/db:/var/lib/casaos/db
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    ports:
      - 5000:5000
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    hostname: "{ServiceName}"
minVersion: 0.14.0
