cosmos-installer: null
name: big-bear-onedev
services:
  "{ServiceName}-big-bear-onedev":
    container_name: "{ServiceName}-big-bear-onedev"
    image: 1dev/server:10.9.0
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-onedev-data:/opt/onedev"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - hibernate_dialect=io.onedev.server.persistence.PostgreSQLDialect
      - hibernate_connection_driver_class=org.postgresql.Driver
      - hibernate_connection_url=jdbc:postgresql://big-bear-onedev-db:5432/onedev
      - hibernate_connection_username=bigbear
      - hibernate_connection_password=eea2dad6-2203-45eb-8908-e8ba4d1e7f92
      - initial_user=bigbear
      - initial_password=password
      - initial_email=admin@example.com
      - initial_server_url=http://localhost:6610
    ports:
      - 6610:6610
      - 6611:6611
    depends_on:
      - "{ServiceName}-big-bear-onedev-db"
    networks:
      - big_bear_ondedev_network
    hostname: "{ServiceName}-big-bear-onedev"
  "{ServiceName}-big-bear-onedev-db":
    container_name: "{ServiceName}-big-bear-onedev-db"
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bigbear
      - POSTGRES_PASSWORD=eea2dad6-2203-45eb-8908-e8ba4d1e7f92
      - POSTGRES_DB=onedev
    volumes:
      - "{ServiceName}-big-bear-onedev-db-data:/var/lib/postgresql/data"
    networks:
      - big_bear_ondedev_network
    hostname: "{ServiceName}-big-bear-onedev-db"
networks:
  big_bear_ondedev_network:
    driver: bridge
minVersion: 0.14.0
