cosmos-installer: null
services:
  app:
    image: linuxserver/wps-office:11.1.0@sha256:3c1e8dc06b08b5f25fd205c50b4c057070e2e1fd2e127532f540cc84f8f350bd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wps-office/config
        target: /config
minVersion: 0.14.0
