cosmos-installer: null
services:
  app:
    image: linuxserver/wps-office:11.1.0@sha256:60bed84aaf47ba56057b89e3069f3721f8cec9f8e5905ed839cbaf879ad35c54
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wps-office/config
        target: /config
minVersion: 0.14.0
