cosmos-installer: null
name: big-bear-retroarch-web
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: inglebard/retroarch-web:latest
    restart: unless-stopped
    environment:
      - ROOT_WWW_PATH="/var/www/html"
    ports:
      - 8080:80
    hostname: "{ServiceName}"
minVersion: 0.14.0
