cosmos-installer: null
services:
  app:
    image: linuxserver/libreoffice:25.8.7@sha256:98f0d5a2dc781b348565611122b88cd87e8d83d4c4a1039296c5831aeb2d327d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/libreoffice/config
        target: /config
minVersion: 0.14.0
