cosmos-installer: null
services:
  app:
    image: linuxserver/wireshark:4.6.6@sha256:1cd396962fb8697e1105feb9d976a0b059362a3e4255a106a7a30bc6dab297ed
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/wireshark/config
        target: /config
minVersion: 0.14.0
