cosmos-installer: null
name: big-bear-guacamole
services:
  "{ServiceName}-guacd":
    image: guacamole/guacd:1.6.0
    restart: always
    container_name: "{ServiceName}-guacd"
    hostname: "{ServiceName}-guacd"
  "{ServiceName}-app":
    image: guacamole/guacamole:1.6.0
    restart: always
    links:
      - guacd
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=mysql
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
    ports:
      - 8090:8080
    container_name: "{ServiceName}-app"
    hostname: "{ServiceName}-app"
  "{ServiceName}-mysql":
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
    volumes:
      - "{ServiceName}-mysql-data:/var/lib/mysql"
    container_name: "{ServiceName}-mysql"
    hostname: "{ServiceName}-mysql"
minVersion: 0.14.0
