cosmos-installer: null
# Name of the configuration: big-bear-guacamole
# Define the services required for the application
services:
  # guacd service configuration
  guacd:
    # Docker image to use for this service
    image: guacamole/guacd:1.6.0@sha256:8974eaa9ba32f713daf311e7cc8cd7e4cdfba1edea39eed75524e78ef4b08f4f
    # Restart policy for the container
    restart: always
  # app service configuration
  app:
    image: guacamole/guacamole:1.6.0@sha256:f344085e618bb05e22b964b0208dbd06d3468275bac70206f93805245e067b40
    restart: always
    # Link this service to the guacd service
    links:
      - guacd
    # Environment variables for the app service
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=mysql
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
    # Map port 8090 on the host to port 8080 on the container
    ports:
      - 8090:8080
  # mysql service configuration
  mysql:
    image: mysql:5.7@sha256:4bc6bc963e6d8443453676cae56536f4b8156d78bae03c0145cbe47c2aad73bb
    restart: always
    # Environment variables for the MySQL service
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=some_password
    # Volume mapping for persistent storage
    volumes:
      - big-bear-guacamole_mysql:/var/lib/mysql
volumes:
  big-bear-guacamole_mysql:
    name: big-bear-guacamole_mysql
    driver: local
minVersion: 0.14.0
