cosmos-installer: null
services:
  app:
    image: linuxserver/signal:8.29.0@sha256:3eb5e94b6311a74e90b627008782b6c14cefb9167aab5f0709ff3257840e8919
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
minVersion: 0.14.0
