cosmos-installer: null
services:
  app:
    image: linuxserver/signal:8.27.0@sha256:86d2bd83079eb0aa6337b4d86e602c912c70cb5d7c942cc99ce033cc9d80f336
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
minVersion: 0.14.0
