cosmos-installer: null
services:
  app:
    image: linuxserver/signal:8.28.0@sha256:1552d343e845d1246728a5894f53e0c42804adedcd1a1a36af7f5aff40cf8d8b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/signal/config
        target: /config
minVersion: 0.14.0
