cosmos-installer: null
services:
  app:
    image: linuxserver/synclounge:5.2.35@sha256:4bfe71ceebad2de95736a5588e12dbd96af050405b77f952bded5d805fe0765c
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
minVersion: 0.14.0
