cosmos-installer: null
services:
  app:
    image: linuxserver/synclounge:5.2.35@sha256:0d21be07263d4b0187a290649d949ecb899bc8fa9994b3d1648546ca7e054ce7
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
minVersion: 0.14.0
