cosmos-installer: null
services:
  app:
    image: linuxserver/synclounge:5.2.35@sha256:aae78ae2936b214d6733d56cbf3dd42fd9c79bcdf4655c00403b704dff9a9a69
    restart: unless-stopped
    environment:
      AUTH_LIST: ''
    ports:
      - target: 8088
        published: 8088
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/synclounge/config
        target: /config
minVersion: 0.14.0
