cosmos-installer: null
services:
  app:
    image: linuxserver/raneto:0.18.1@sha256:72464f21361a3a10ac3aaba97bbd60d3ca63e06ee7209fe4a1d40c62c4705c03
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/raneto/config
        target: /config
minVersion: 0.14.0
