cosmos-installer: null
services:
  app:
    image: linuxserver/altus:5.8.1@sha256:5f40cab7138d484196890ed773a2a71ed78576a28ad0b73a5d7ff9ab0de3d323
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/altus/config
        target: /config
minVersion: 0.14.0
