cosmos-installer: null
services:
  app:
    image: linuxserver/vscodium-web:1.135.06055@sha256:252430e3b9f3b2fdd903170b88802d34457042866cd8920625daaec435d7f32c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CONNECTION_TOKEN: ''
      CONNECTION_TOKEN_FILE: ''
      SUDO_PASSWORD: ''
      SUDO_PASSWORD_HASH: ''
      CODE_ARGS: ''
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium-web/config
        target: /config
minVersion: 0.14.0
