# Configuration for playitgg setup

# Name of the big-bear-playitgg application
name: big-bear-playitgg
# Service definitions for the big-bear-playitgg application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: playitgg
    # Image to be used for the container
    image: dysta/playitgg:1.1.0
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local playitgg directory to /secrets inside the container
      - playitgg_secrets:/secrets
volumes:
  playitgg_secrets: {}
