cosmos-installer: null
name: big-bear-rallly
services:
  "{ServiceName}-big-bear-rallly":
    container_name: "{ServiceName}-big-bear-rallly"
    image: lukevella/rallly:3.9.1
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://rallly:f87c7126-f816-47ef-9193-2e5eec763fcd@big-bear-rallly-db/big-bear-rallly
      - SECRET_PASSWORD=0f6f292d-c78c-4709-920d-e3b6361eb5b5
      - NEXT_PUBLIC_BASE_URL=http://[YOUR_CASAOS_IP]:3000
      - NOREPLY_EMAIL=noreply@example.com
      - SUPPORT_EMAIL=support@example.com
      - SMTP_HOST=[YOUR_CASAOS_IP]
      - SMTP_PORT=1025
      - SMTP_SECURE=
      - SMTP_USER=
      - SMTP_PWD=
      - SMTP_TLS_ENABLED=
      - ALLOWED_EMAILS=
    ports:
      - 3000:3000
    networks:
      - big_bear_rally_network
    depends_on:
      - "{ServiceName}-big-bear-rallly-db"
    hostname: "{ServiceName}-big-bear-rallly"
  "{ServiceName}-big-bear-rallly-db":
    container_name: "{ServiceName}-big-bear-rallly-db"
    image: postgres:14
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-rallly-db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=f87c7126-f816-47ef-9193-2e5eec763fcd
      - POSTGRES_DB=big-bear-rallly
      - POSTGRES_USER=rallly
    networks:
      - big_bear_rally_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U rallly
      interval: 5s
      timeout: 5s
      retries: 5
    hostname: "{ServiceName}-big-bear-rallly-db"
networks:
  big_bear_rally_network:
    driver: bridge
minVersion: 0.14.0
