# Configuration for dockge setup

# Name of the big-bear-dockge application
name: big-bear-dockge
# Service definitions for the big-bear-dockge application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-dockge
    # Image to be used for the container
    image: louislam/dockge:1.5.0
    # Environment variables
    environment:
      # Tell Dockge where is your stacks directory
      DOCKGE_STACKS_DIR: "/DATA/AppData/big-bear-dockge/stacks"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge_data:/app/data
      - dockge_stacks:/DATA/AppData/big-bear-dockge/stacks
    # Ports mapping between host and container
    ports:
      - 5001:5001
volumes:
  dockge_data: {}
  dockge_stacks: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: dockge
    description: Dockge
    useHost: true
    target: http://localhost:5001
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
