# Configuration for plex setup

# Name of the big-bear-plex application
name: big-bear-plex
# Service definitions for the big-bear-plex application
services:
  # Service name: big-bear-plex
  # The `big-bear-plex` service definition
  big-bear-plex:
    # Name of the container
    container_name: big-bear-plex
    # Image to be used for the container
    image: linuxserver/plex:1.42.2
    environment:
      - PUID=1000 # specify the user id
      - PGID=1000 # specify the group id
      - TZ=Etc/UTC # specify a timezone to use.
      - VERSION=docker # Set whether to update plex or not.
      - PLEX_CLAIM= #optional Optionally you can obtain a claim token from https://plex.tv/claim and input here. Keep in mind that the claim tokens expire within 4 minutes.
    # Container restart policy
    restart: unless-stopped
    # Network mode for the container
    network_mode: host
    # Volumes to be mounted to the container
    volumes:
      - plex_config:/config
      - plex_tv:/tv
      - plex_movies:/movies
volumes:
  plex_config: {}
  plex_tv: {}
  plex_movies: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: plex
    description: Plex
    useHost: true
    target: http://localhost:32400
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
