cosmos-installer: null
name: big-bear-plex
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: linuxserver/plex:1.41.9
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=
    restart: unless-stopped
    network_mode: host
    volumes:
      - "{ServiceName}-data:/config"
      - "{ServiceName}-data-2:/tv"
      - "{ServiceName}-data-3:/movies"
    hostname: "{ServiceName}"
minVersion: 0.14.0
