# Configuration for lancache setup

# Name of the big-bear-lancache application
name: big-bear-lancache
# Service definitions for the big-bear-lancache application
services:
  # Service name: app
  app:
    image: lancachenet/monolithic:latest # Docker image for the caching service
    environment:
      # Toggle for load balancer usage or separate IPs for each service
      - USE_GENERIC_CACHE=true
      # IPs for lancache monolithic instance; affects DNS resolution
      - LANCACHE_IP=10.0.39.1
      # Host IP for the DNS server binding
      - DNS_BIND_IP=10.0.39.1
      # Upstream DNS for forwarded lookups
      - UPSTREAM_DNS=8.8.8.8
      # Local storage path for cache data
      - CACHE_ROOT=./lancache
      # Customizable disk cache size
      - CACHE_DISK_SIZE=2000g
      # Memory allocation for nginx cache indexing
      - CACHE_INDEX_SIZE=500m
      # Maximum age for cached content
      - CACHE_MAX_AGE=3650d
      # Container timezone setting for log timestamps
      - TZ=UTC
    restart: unless-stopped
    ports:
      - 8080:80
      - 10443:443
    volumes:
      # Mount points for cache and logs
      - lancache_cache:/data/cache
      - lancache_logs:/data/logs
  # DNS service configuration
  dns:
    image: lancachenet/lancache-dns:latest # Docker image for DNS service
    environment:
      # Toggle for load balancer usage or separate IPs for each service
      - USE_GENERIC_CACHE=true
      # IPs for lancache monolithic instance; affects DNS resolution
      - LANCACHE_IP=10.0.39.1
      # Host IP for the DNS server binding
      - DNS_BIND_IP=10.0.39.1
      # Upstream DNS for forwarded lookups
      - UPSTREAM_DNS=8.8.8.8
      # Local storage path for cache data
      - CACHE_ROOT=./lancache
      # Customizable disk cache size
      - CACHE_DISK_SIZE=2000g
      # Memory allocation for nginx cache indexing
      - CACHE_INDEX_SIZE=500m
      # Maximum age for cached content
      - CACHE_MAX_AGE=3650d
      # Container timezone setting for log timestamps
      - TZ=UTC
    restart: unless-stopped
    ports:
      - 53:53/udp
      - 53:53/tcp
volumes:
  lancache_cache: {}
  lancache_logs: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: lancache
    description: LAN Cache
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
