cosmos-installer: null
name: big-bear-lancache
services:
  "{ServiceName}-app":
    image: lancachenet/monolithic:latest
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=10.0.39.1
      - DNS_BIND_IP=10.0.39.1
      - UPSTREAM_DNS=8.8.8.8
      - CACHE_ROOT=./lancache
      - CACHE_DISK_SIZE=2000g
      - CACHE_INDEX_SIZE=500m
      - CACHE_MAX_AGE=3650d
      - TZ=UTC
    restart: unless-stopped
    ports:
      - 8080:80
      - 10443:443
    volumes:
      - "{ServiceName}-app-data:/data/cache"
      - "{ServiceName}-app-data-2:/data/logs"
    container_name: "{ServiceName}-app"
    hostname: "{ServiceName}-app"
  "{ServiceName}-dns":
    image: lancachenet/lancache-dns:latest
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=10.0.39.1
      - DNS_BIND_IP=10.0.39.1
      - UPSTREAM_DNS=8.8.8.8
      - CACHE_ROOT=./lancache
      - CACHE_DISK_SIZE=2000g
      - CACHE_INDEX_SIZE=500m
      - CACHE_MAX_AGE=3650d
      - TZ=UTC
    restart: unless-stopped
    ports:
      - 53:53/udp
      - 53:53/tcp
    container_name: "{ServiceName}-dns"
    hostname: "{ServiceName}-dns"
minVersion: 0.14.0
