# Configuration for big-bear-umbrel setup

# Name of the big-bear-umbrel application
name: big-bear-umbrel
# Service definitions for the big-bear-umbrel application
services:
  # Service name: big-bear-umbrel
  # The `big-bear-umbrel` service definition
  big-bear-umbrel:
    # Name of the container
    container_name: big-bear-umbrel
    # Image to be used for the container
    image: dockurr/umbrel:1.4.0
    # Container restart policy
    restart: unless-stopped
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "8080:80"
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID directory to /data inside the container
      - umbrel_os_data:/data
      # Mounting docker.sock to allow docker management via Umbrel
      - /var/run/docker.sock:/var/run/docker.sock
    # Stop grace period for the container
    stop_grace_period: 1m
volumes:
  umbrel_os_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: umbrel-os
    description: Umbrel OS
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
