cosmos-installer: null
name: big-bear-umbrel
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: dockurr/umbrel:1.2.2
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - "{ServiceName}-data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    stop_grace_period: 1m
    hostname: "{ServiceName}"
minVersion: 0.14.0
