# Configuration for tugtainer setup

# Name of the big-bear-tugtainer application
name: big-bear-tugtainer
# Service definitions for the big-bear-tugtainer application
services:
  # Service name: big-bear-tugtainer
  # The `big-bear-tugtainer` service definition
  big-bear-tugtainer:
    # Name of the container
    container_name: big-bear-tugtainer
    # Image to be used for the container
    image: quenary/tugtainer:v1.3.0
    # Container restart policy
    restart: unless-stopped
    # Ports to expose from the container
    ports:
      - "9412:80"
    # Environment variables for the container
    environment:
      TZ: "UTC"
      LOG_LEVEL: "warning"
      JWT_SECRET_KEY: "your-secret-key-here"
      ACCESS_TOKEN_LIFETIME_MIN: "5"
      REFRESH_TOKEN_LIFETIME_MIN: "43200"
      HTTPS: "FALSE"
    # Volumes to be mounted to the container
    volumes:
      - tugtainer_data:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  tugtainer_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: tugtainer
    description: Tugtainer
    useHost: true
    target: http://localhost:9412
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
