# Configuration for uptime-kuma setup

# Name of the big-bear-uptime-kuma application
name: big-bear-uptime-kuma
# Service definitions for the big-bear-uptime-kuma application
services:
  # Service name: app
  # The `app` service definition includes the docker image, container name, volume mappings, port configurations, restart policy, and CasaOS specific settings.
  app:
    # Docker image to use for the app service
    image: louislam/uptime-kuma:1
    # Custom container name for identification
    container_name: uptime-kuma
    # Volume mappings: Maps host directory to container directory for persistent storage
    volumes:
      - uptime_kuma_data:/app/data
    # Port mapping: Maps a port on the host to a port on the container
    ports:
      - "3001:3001" # <Host Port>:<Container Port>
    # Restart policy: Always restart the container if it stops
    restart: always
volumes:
  uptime_kuma_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: uptime-kuma
    description: Uptime Kuma
    useHost: true
    target: http://localhost:3001
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
