# Configuration for eufy-security-ws setup

# Name of the big-bear-eufy-security-ws application
name: big-bear-eufy-security-ws
# Service definitions for the big-bear-eufy-security-ws application
services:
  # Service name: big-bear-eufy-security-ws
  # The `big-bear-eufy-security-ws` service definition
  big-bear-eufy-security-ws:
    # Name of the container
    container_name: big-bear-eufy-security-ws
    # Image to be used for the container
    image: bropat/eufy-security-ws:1.9.3
    # Environment variables for the container
    environment:
      USERNAME: "[EUFY_USERNAME]"
      PASSWORD: "[EUFY_PASSWORD]"
      COUNTRY: "US"
      LANGUAGE: "en"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local data directory to /data inside the container
      - eufy_security_ws_data:/data
    # Network configuration
    network_mode: host
volumes:
  eufy_security_ws_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: eufy-security-ws
    description: Eufy Security WS
    useHost: true
    target: http://localhost:3000
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
