cosmos-installer: null
name: big-bear-libretranslate
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: libretranslate/libretranslate:v1.6.2
    restart: unless-stopped
    environment:
      - LT_API_KEYS=true
      - LT_API_KEYS_DB_PATH=/app/db/api_keys.db
      - LT_UPDATE_MODELS=true
      - LT_LOAD_ONLY=en,fr,es,de,it,pt,ru,ja,zh
    volumes:
      - "{ServiceName}-data:/app/db"
      - "{ServiceName}-data-2:/home/libretranslate/.local"
    ports:
      - 5000:5000
    tty: true
    healthcheck:
      test:
        - CMD-SHELL
        - ./venv/bin/python scripts/healthcheck.py
    hostname: "{ServiceName}"
minVersion: 0.14.0
