cosmos-installer: null
services:
  app:
    image: linuxserver/inkscape:1.4.2@sha256:5f9b8b052072ec001296d1d555039da2667cc1b0fd91f14ae912f23b69a56a56
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/inkscape/config
        target: /config
minVersion: 0.14.0
