cosmos-installer: null
name: big-bear-ncdu
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: bigbeartechworld/big-bear-ncdu:0.0.2
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7681:7681
    environment:
      - NCDU_PATH=/
    hostname: "{ServiceName}"
minVersion: 0.14.0
