# Configuration for ejbca-ce setup

# Name of the big-bear-ejbca-ce application
name: big-bear-ejbca-ce
# Service definitions for the big-bear-ejbca-ce application
services:
  # Service name: app
  # The `app` service definition
  big-bear-ejbca-ce:
    # Name of the container
    container_name: big-bear-ejbca-ce
    # Image to be used for the container
    image: keyfactor/ejbca-ce:9.1.1
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local ejbca-ce/persistent directory to /mnt/persistent inside the container
      - ejbca_ce_persistent:/mnt/persistent
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 8080 of the container
      - "8080:8080"
      # Mapping port 8443 of the host to port 8443 of the container
      - "8443:8443"
    # Environment variables
    environment:
      - TLS_SETUP_ENABLED=simple
volumes:
  ejbca_ce_persistent: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: ejbca-ce
    description: EJBCA Community
    useHost: true
    target: http://localhost:8443
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
