cosmos-installer: null
name: big-bear-ejbca-ce
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: keyfactor/ejbca-ce:9.0.0
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/mnt/persistent"
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      - TLS_SETUP_ENABLED=simple
    hostname: "{ServiceName}"
minVersion: 0.14.0
