cosmos-installer: null
services:
  app:
    image: linuxserver/gzdoom:4.14.2@sha256:8478fecca91fbb34a975b4822fb5d391a354873e118a9cb6d99ed0a85ea82023
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gzdoom/config
        target: /config
minVersion: 0.14.0
