cosmos-installer: null
services:
  app:
    image: linuxserver/gzdoom:4.14.2@sha256:dc74ced86ff8625f16c95875b6d4db4efee64789b1a5a4fe7c145ca05b0d7b14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gzdoom/config
        target: /config
minVersion: 0.14.0
