# Configuration for erugo setup

# Name of the big-bear-erugo application
name: big-bear-erugo
# Service definitions for the big-bear-erugo application
services:
  # Service name: big-bear-erugo
  # The `big-bear-erugo` service definition
  big-bear-erugo:
    # Name of the container
    container_name: big-bear-erugo
    # Image to be used for the container
    image: wardy784/erugo:0.1.1
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting storage directory to allow erugo to save data
      - erugo_storage:/var/www/html/storage
    # Ports mapping between host and container
    ports:
      # Mapping port 9997 of the host to port 80 of the container
      - "9997:80"
volumes:
  erugo_storage: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: erugo
    description: Erugo
    useHost: true
    target: http://localhost:9997
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
