cosmos-installer: null
name: big-bear-erugo
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: wardy784/erugo:0.1.1
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/var/www/html/storage"
    ports:
      - 9997:80
    hostname: "{ServiceName}"
minVersion: 0.14.0
