# Configuration for invoice-ninja setup

# Name of the big-bear-invoice-ninja application
name: big-bear-invoice-ninja
# Service definitions for the big-bear-invoice-ninja application
services:
  big-bear-invoice-ninja:
    image: invoiceninja/invoiceninja:5.12.28
    container_name: big-bear-invoice-ninja
    restart: unless-stopped
    user: 1500:1500
    environment:
      - IN_USER_EMAIL=admin@bigbeartechworld.com
      - IN_PASSWORD=ad178c4b-302f-44e6-937f-8c7808f23795
      - APP_URL=http://big-bear-invoice-ninja-web
      - APP_KEY=base64:4doW1cidLuSqm7Z/BhPu/bn5HGnCKyEcSSlbVPTYYRU=
      - APP_CIPHER=AES-256-CBC
      - DB_HOST=big-bear-invoice-ninja-db
      - DB_PORT=3306
      - DB_DATABASE=ninja
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - REQUIRE_HTTPS=false
      - QUEUE_CONNECTION=database
      - IS_DOCKER=TRUE
    volumes:
      - invoice_ninja_data_public:/var/www/app/public
      - invoice_ninja_data_storage:/var/www/app/storage
      - invoice_ninja_data_php_php.ini:/usr/local/etc/php/php.ini
      - invoice_ninja_data_php_php_cli.ini:/usr/local/etc/php/php-cli.ini
    depends_on:
      - big-bear-invoice-ninja-db
    networks:
      - big-bear-invoice-ninja-network
  big-bear-invoice-ninja-web:
    # Name of the container
    container_name: big-bear-invoice-ninja-web
    # Image to be used for the container
    image: nginx:1.29
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - invoice_ninja_data_nginx_invoice_ninja.conf:/etc/nginx/conf.d/default.conf
      - invoice_ninja_data_public:/var/www/app/public
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 80 of the container
      - "8080:80"
    networks:
      - big-bear-invoice-ninja-network
  big-bear-invoice-ninja-db:
    image: mariadb:10.4
    container_name: big-bear-invoice-ninja-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=ad178c4b-302f-44e6-937f-8c7808f23795
      - MARIADB_USER=ninja
      - MARIADB_PASSWORD=ninja
      - MARIADB_DATABASE=ninja
    volumes:
      - invoice_ninja_data_mysql:/var/lib/mysql
    networks:
      - big-bear-invoice-ninja-network
    depends_on:
      - big-bear-invoice-ninja-init
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
  big-bear-invoice-ninja-init:
    image: bash:5.3.3
    container_name: big-bear-invoice-ninja-init
    volumes:
      - invoice_ninja_data:/tmp/data
    command: ["/bin/sh", "-c", "if [ ! -f /tmp/data/.init_complete ]; then echo 'Starting initialization process...' && if [ -f /tmp/data/init/init.sh ]; then echo 'Found init.sh, making it executable...' && chmod +x /tmp/data/init/init.sh && echo 'Executing init.sh...' && /tmp/data/init/init.sh && echo 'init.sh execution completed.' && touch /tmp/data/.init_complete && echo 'Initialization process finished.'; else echo 'Error: /tmp/data/init/init.sh not found!' && exit 1; fi; else echo 'Initialization already completed. Exiting.'; fi && exit 0"]
    networks:
      - big-bear-invoice-ninja-network
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  big-bear-invoice-ninja-network:
    driver: bridge
volumes:
  invoice_ninja_data_public: {}
  invoice_ninja_data_storage: {}
  invoice_ninja_data_php_php.ini: {}
  invoice_ninja_data_php_php_cli.ini: {}
  invoice_ninja_data_nginx_invoice_ninja.conf: {}
  invoice_ninja_data_mysql: {}
  invoice_ninja_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: invoice-ninja
    description: Invoice Ninja
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
