cosmos-installer: null
name: big-bear-invoice-ninja
services:
  "{ServiceName}-big-bear-invoice-ninja":
    image: invoiceninja/invoiceninja:5.11.2
    container_name: "{ServiceName}-big-bear-invoice-ninja"
    restart: unless-stopped
    user: 1500:1500
    environment:
      - IN_USER_EMAIL=admin@bigbeartechworld.com
      - IN_PASSWORD=ad178c4b-302f-44e6-937f-8c7808f23795
      - APP_URL=http://big-bear-invoice-ninja-web
      - APP_KEY=base64:4doW1cidLuSqm7Z/BhPu/bn5HGnCKyEcSSlbVPTYYRU=
      - APP_CIPHER=AES-256-CBC
      - DB_HOST={ServiceName}-big-bear-invoice-ninja-db
      - DB_PORT=3306
      - DB_DATABASE=ninja
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - REQUIRE_HTTPS=false
      - QUEUE_CONNECTION=database
      - IS_DOCKER=TRUE
    volumes:
      - "{ServiceName}-big-bear-invoice-ninja-data:/var/www/app/public"
      - "{ServiceName}-big-bear-invoice-ninja-data-2:/var/www/app/storage"
      - "{ServiceName}-big-bear-invoice-ninja-data-3:/usr/local/etc/php/php.ini"
      - "{ServiceName}-big-bear-invoice-ninja-data-4:/usr/local/etc/php/php-cli\
        .ini"
    depends_on:
      - "{ServiceName}-big-bear-invoice-ninja-db"
    networks:
      - big-bear-invoice-ninja-network
    hostname: "{ServiceName}-big-bear-invoice-ninja"
  "{ServiceName}-big-bear-invoice-ninja-web":
    container_name: "{ServiceName}-big-bear-invoice-ninja-web"
    image: nginx:1.27
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-invoice-ninja-web-data:/etc/nginx/conf.d/defaul\
        t.conf"
      - "{ServiceName}-big-bear-invoice-ninja-web-data-2:/var/www/app/public"
    ports:
      - 8080:80
    networks:
      - big-bear-invoice-ninja-network
    hostname: "{ServiceName}-big-bear-invoice-ninja-web"
  "{ServiceName}-big-bear-invoice-ninja-db":
    image: mariadb:10.4
    container_name: "{ServiceName}-big-bear-invoice-ninja-db"
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=ad178c4b-302f-44e6-937f-8c7808f23795
      - MARIADB_USER=ninja
      - MARIADB_PASSWORD=ninja
      - MARIADB_DATABASE=ninja
    volumes:
      - "{ServiceName}-big-bear-invoice-ninja-db-data:/var/lib/mysql"
    networks:
      - big-bear-invoice-ninja-network
    depends_on:
      - "{ServiceName}-big-bear-invoice-ninja-init"
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --wait_timeout=28800
      - --log-warnings=0
    hostname: "{ServiceName}-big-bear-invoice-ninja-db"
  "{ServiceName}-big-bear-invoice-ninja-init":
    image: bash:5.2.37
    container_name: "{ServiceName}-big-bear-invoice-ninja-init"
    volumes:
      - "{ServiceName}-big-bear-invoice-ninja-init-data:/tmp/data"
    command:
      - /bin/sh
      - -c
      - "if [ ! -f /tmp/data/.init_complete ]; then echo 'Starting
        initialization process...' && if [ -f /tmp/data/init/init.sh ]; then
        echo 'Found init.sh, making it executable...' && chmod +x
        /tmp/data/init/init.sh && echo 'Executing init.sh...' &&
        /tmp/data/init/init.sh && echo 'init.sh execution completed.' && touch
        /tmp/data/.init_complete && echo 'Initialization process finished.';
        else echo 'Error: /tmp/data/init/init.sh not found!' && exit 1; fi; else
        echo 'Initialization already completed. Exiting.'; fi && exit 0"
    networks:
      - big-bear-invoice-ninja-network
    restart: no
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"
    hostname: "{ServiceName}-big-bear-invoice-ninja-init"
networks:
  big-bear-invoice-ninja-network:
    driver: bridge
minVersion: 0.14.0
