cosmos-installer: null
name: big-bear-mealie
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: hkotel/mealie:v2.5.0
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/app/data"
    ports:
      - 9925:9000
    hostname: "{ServiceName}"
minVersion: 0.14.0
