cosmos-installer: null
name: big-bear-chatpad
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/deiucanta/chatpad:f45cd53bc410412610c1ba1cbd84cd137d8e167d
    restart: unless-stopped
    ports:
      - 8080:80
    hostname: "{ServiceName}"
minVersion: 0.14.0
