# Configuration for netalertx setup

# Name of the big-bear-netalertx application
name: big-bear-netalertx
# Service definitions for the big-bear-netalertx application
services:
  # Service name: big-bear-netalertx
  # The `big-bear-netalertx` service definition
  big-bear-netalertx:
    # Name of the container
    container_name: big-bear-netalertx
    # Image to be used for the container
    image: jokobsk/netalertx:25.10.1
    # Container restart policy
    restart: unless-stopped
    # Make the container privileged
    privileged: true
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/config directory to /app/config inside the container
      - netalertx_config:/app/config
      # Mounting the local /DATA/AppData/$AppID/db directory to /app/db inside the container
      - netalertx_db:/app/db
    # Environment variables
    environment:
      - TZ=UTC
      - PORT=8080
      # ❗ DANGER ZONE BELOW - Setting ALWAYS_FRESH_INSTALL=true will delete the content of the /db & /config folders
      - ALWAYS_FRESH_INSTALL=false
    # Network mode for the container
    network_mode: host
volumes:
  netalertx_config: {}
  netalertx_db: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: netalertx
    description: NetAlertX
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
