name: big-bear-chrome # Name of the CasaOS application
services:
  chrome:
    container_name: big-bear-chrome # Name of the Docker container
    image: kasmweb/chrome:1.15.0-rolling # Docker image for the chrome browser
    ports:
      - "6902:6901" # Expose port 6901 for VNC access
    environment:
      - VNC_PW=casaos # Set the VNC password to 'casaos'
      - LAUNCH_URL=https://community.bigbeartechworld.com/ # Set the default URL to Big Bear Tech World
    shm_size: 512m # Allocate 512 MB of shared memory
    volumes:
      - chrome_Downloads:/home/kasm-user/Downloads # Mount the host directory to the container's Downloads directory
volumes:
  chrome_Downloads: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: chrome
    description: chrome
    useHost: true
    target: http://localhost:6902
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
