cosmos-installer: null
services:
  app:
    image: linuxserver/duplicati:2.4.0@sha256:1a53819a0cd6aaaa4245d5064a55d9797c1f4c8565ffd3bddc001a2290c8ed02
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SETTINGS_ENCRYPTION_KEY: ''
      CLI_ARGS: ''
      DUPLICATI__WEBSERVICE_PASSWORD: ''
    ports:
      - target: 8200
        published: 8200
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/duplicati/config
        target: /config
      - type: bind
        source: /DATA/AppData/duplicati/backups
        target: /backups
      - type: bind
        source: /DATA/AppData/duplicati/source
        target: /source
minVersion: 0.14.0
