cosmos-installer: null
name: big-bear-rocket-chat
services:
  "{ServiceName}-app":
    container_name: "{ServiceName}-app"
    image: rocket.chat:6.5.3
    restart: unless-stopped
    environment:
      MONGO_OPLOG_URL: mongodb://db:27017/local
      ROOT_URL: http://localhost:3000
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rocketchat-net
    hostname: "{ServiceName}-app"
  "{ServiceName}-db":
    image: mongo:4.4.28
    container_name: "{ServiceName}-db"
    volumes:
      - "{ServiceName}-db-data:/data/db"
    healthcheck:
      test:
        - CMD
        - mongo
        - --eval
        - db.stats()
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rocketchat-net
    hostname: "{ServiceName}-db"
networks:
  rocketchat-net:
    driver: bridge
minVersion: 0.14.0
