# Configuration for trilium setup

# Name of the big-bear-trilium application
name: big-bear-trilium
# Service definitions for the big-bear-trilium application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-trilium
    # Image to be used for the container
    image: triliumnext/trilium:v0.99.3
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/data directory to /home/node/trilium-data inside the container
      - trilium_data:/home/node/trilium-data
    # Ports mapping between host and container
    ports:
      # Mapping port 8080 of the host to port 8080 of the container
      - "8080:8080"
volumes:
  trilium_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: trilium
    description: Trilium
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
