cosmos-installer: null
services:
  app:
    image: linuxserver/pidgin:2.14.14@sha256:70c7c1741aaf59781f2e6afbe0a30044c61eb94b5359405a691416b0700bf904
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pidgin/config
        target: /config
minVersion: 0.14.0
