cosmos-installer: null
services:
  app:
    image: linuxserver/opera:137.0.6036@sha256:8c24ac8975f6bae95cf60481be8401c2850552633b2a6dfa9a5971edad8b1960
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      OPERA_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/opera/config
        target: /config
minVersion: 0.14.0
