cosmos-installer: null
services:
  app:
    image: linuxserver/freshrss:1.30.0@sha256:5358f396069b36f1399b16a4a368869ed8c1ccca16d15778bbc7782b76fba57e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freshrss/config
        target: /config
minVersion: 0.14.0
