cosmos-installer: null
services:
  app:
    image: linuxserver/qdirstat:2.0.20260928@sha256:6551ad061d5821c9c69147b230c45016ee453dccad15c69a3ad608da1ea33c67
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/qdirstat/config
        target: /config
      - type: bind
        source: /DATA/AppData/qdirstat/data
        target: /data
minVersion: 0.14.0
