cosmos-installer: null
# Configuration for big-bear-wud setup

# Name of the big-bear-wud application
# Service definitions for the big-bear-wud application
services:
  # Service definition for the main application
  app:
    image: fmartinou/whats-up-docker:6.6.1@sha256:7cbdfa9bb56de7ad820e3efea16205c3cf09e5f06192436530c5c798964607f0
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
minVersion: 0.14.0
