cosmos-installer: null
name: big-bear-docmost
services:
  "{ServiceName}-big-bear-docmost":
    container_name: "{ServiceName}-big-bear-docmost"
    image: docmost/docmost:0.10.2
    restart: unless-stopped
    environment:
      - APP_URL=http://localhost:3000
      - APP_SECRET=d4e8f3c3-72b9-4003-be4c-168f13024853
      - DATABASE_URL=postgresql://docmost:ea9dee39-c390-4a88-be39-8034f4bb9b82@{ServiceName}-big-bear-docmost-db:5432/docmost?schema
      - REDIS_URL=redis://big-bear-docmost-redis:6379/0
    volumes:
      - "{ServiceName}-big-bear-docmost-data:/app/data/storage"
    ports:
      - 3000:3000
    networks:
      - big-bear-docmost-network
    depends_on:
      - "{ServiceName}-big-bear-docmost-db"
      - "{ServiceName}-big-bear-docmost-redis"
    hostname: "{ServiceName}-big-bear-docmost"
  "{ServiceName}-big-bear-docmost-db":
    container_name: "{ServiceName}-big-bear-docmost-db"
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=docmost
      - POSTGRES_USER=docmost
      - POSTGRES_PASSWORD=ea9dee39-c390-4a88-be39-8034f4bb9b82
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-docmost-db-data:/var/lib/postgresql/data"
    networks:
      - big-bear-docmost-network
    hostname: "{ServiceName}-big-bear-docmost-db"
  "{ServiceName}-big-bear-docmost-redis":
    container_name: "{ServiceName}-big-bear-docmost-redis"
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-docmost-redis-data:/data"
    networks:
      - big-bear-docmost-network
    hostname: "{ServiceName}-big-bear-docmost-redis"
networks:
  big-bear-docmost-network:
    driver: bridge
minVersion: 0.14.0
