# Configuration for dbgate setup

# Name of the big-bear-dbgate application
name: big-bear-dbgate
# Service definitions for the big-bear-dbgate application
services:
  # Service name: big-bear-dbgate
  # The `big-bear-dbgate` service definition
  big-bear-dbgate:
    # Name of the container
    container_name: big-bear-dbgate
    # Image to be used for the container
    image: dbgate/dbgate:6.6.5-alpine
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local homarr/configs directory to /app/data/configs inside the container
      - dbgate_config:/root/.dbgate
    # Ports mapping between host and container
    ports:
      # Mapping port 3000 of the host to port 3000 of the container
      - "3000:3000"
volumes:
  dbgate_config: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: dbgate
    description: DBGate
    useHost: true
    target: http://localhost:3000
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
