cosmos-installer: null
services:
  app:
    image: linuxserver/handbrake:1.11.2@sha256:283d18aa7029adec4ede8c7df160300a3cbf942560d8122aae2e2f35d92e0826
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
minVersion: 0.14.0
