cosmos-installer: null
services:
  app:
    image: linuxserver/handbrake:1.11.2@sha256:fdf989652f8d616596d1753dfaa0a53e7c559051b7ba8bf25a945fd7a1d9e824
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/handbrake/config
        target: /config
minVersion: 0.14.0
