cosmos-installer: null
services:
  app:
    image: linuxserver/pwndrop:1.0.1@sha256:2e5428b3c612d0b8413e584539f444b59ddc388d31d71bb5cc6fd348286a5904
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      SECRET_PATH: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pwndrop/config
        target: /config
minVersion: 0.14.0
