cosmos-installer: null
services:
  app:
    image: linuxserver/webgrabplus:5.6.1@sha256:8d5dd403b0f16d4a96ff19a8360ee75193f9429c95bd343c7a2922075fefc056
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webgrabplus/config
        target: /config
      - type: bind
        source: /DATA/AppData/webgrabplus/data
        target: /data
minVersion: 0.14.0
