cosmos-installer: null
services:
  app:
    image: linuxserver/remmina:1.4.43@sha256:a3a1bcd96d73d634d19b80cf1d10422faf9ad5875edb3dcd01d296151d0ed08a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
minVersion: 0.14.0
