cosmos-installer: null
services:
  app:
    image: caddy:2.11.4
    restart: unless-stopped
    ports:
      - target: 80
        published: 48100
        protocol: tcp
      - target: 443
        published: 48101
        protocol: tcp
      - target: 2019
        published: 2019
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/caddy/data
        target: /data
      - type: bind
        source: /DATA/AppData/caddy/config
        target: /config
      - type: bind
        source: /DATA/AppData/caddy/caddyfile
        target: /etc/caddy/caddyfile
minVersion: 0.14.0
