cosmos-installer: null
services:
  app:
    image: linuxserver/krita:5.3.4@sha256:c4c5d196457b839981690a8e242621bddd668a6f845ceefb27c69e142ee18346
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/krita/config
        target: /config
minVersion: 0.14.0
