# Configuration for watchyourlan setup

# Name of the big-bear-watchyourlan application
name: big-bear-watchyourlan
# Service definitions for the big-bear-watchyourlan application
services:
  # Service name: big-bear-watchyourlan
  # The `big-bear-watchyourlan` service definition
  big-bear-watchyourlan:
    # Name of the container
    container_name: big-bear-watchyourlan
    # Image to be used for the container
    image: aceberg/watchyourlan:2.1.4
    # Environment variables to be used for the container
    environment:
      - IFACES="eth0"
      - TZ="UTC"
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-watchyourlan/data directory to /data/WatchYourLAN inside the container
      - watchyourlan_data:/data/WatchYourLAN
    # Network mode to be used for the container
    network_mode: host
volumes:
  watchyourlan_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: watchyourlan
    description: WatchYourLAN
    useHost: true
    target: http://localhost:8840
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
