cosmos-installer: null
services:
  app:
    image: linuxserver/mstream:6.29.0@sha256:fa93d0d7ad01756cc83d7d49252d78517d20871e18d33e171bffd30e865d0156
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mstream/config
        target: /config
      - type: bind
        source: /DATA/AppData/mstream/music
        target: /music
minVersion: 0.14.0
