cosmos-installer: null
services:
  app:
    image: linuxserver/vivaldi:8.2.4133@sha256:b5c17af7f4b5f9475302d9144b532ee5cbb57773a74bc307323c17f83cd0cd7c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      VIVALDI_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vivaldi/config
        target: /config
minVersion: 0.14.0
