cosmos-installer: null
name: big-bear-ihatemoney
services:
  "{ServiceName}-big-bear-ihatemoney":
    container_name: "{ServiceName}-big-bear-ihatemoney"
    image: ihatemoney/ihatemoney:6.1.5
    restart: unless-stopped
    environment:
      SECRET_KEY: 1d58bc34-e7ff-4f6d-a1e4-f319262ed9b8
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://bigbear:password@big-bear-ihatemoney-db/ihatemoney
      ACTIVATE_ADMIN_DASHBOARD: "True"
      ADMIN_PASSWORD: ""
      SESSION_COOKIE_SECURE: "False"
    ports:
      - 8001:8000
    networks:
      - big_bear_ihatemoney_network
    hostname: "{ServiceName}-big-bear-ihatemoney"
  "{ServiceName}-big-bear-ihatemoney-db":
    image: mariadb:10
    container_name: "{ServiceName}-big-bear-ihatemoney-db"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ihatemoney
      MYSQL_USER: bigbear
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - "{ServiceName}-big-bear-ihatemoney-db-data:/var/lib/mysql"
    networks:
      - big_bear_ihatemoney_network
    hostname: "{ServiceName}-big-bear-ihatemoney-db"
networks:
  big_bear_ihatemoney_network:
    driver: bridge
minVersion: 0.14.0
