# Configuration for beszel setup

# Name of the big-bear-beszel application
name: big-bear-beszel
# Service definitions for the big-bear-beszel application
services:
  # Service name: big-bear-beszel
  # The `big-bear-beszel` service definition
  big-bear-beszel:
    # Name of the container
    container_name: big-bear-beszel
    # Image to be used for the container
    image: henrygd/beszel:0.14.1
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - beszel_data:/beszel_data
    # Ports mapping between host and container
    ports:
      # Mapping port 8090 of the host to port 8090 of the container
      - "8090:8090"
volumes:
  beszel_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: beszel
    description: Beszel
    useHost: true
    target: http://localhost:8090
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
