cosmos-installer: null
services:
  app:
    image: linuxserver/yq:4.4.0@sha256:f83757f22c2d330aa56ed1dfc93beb92b488ad2d0085aaa3dd076e6c12f9f260
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/yq/config
        target: /config
minVersion: 0.14.0
