# Configuration for homebridge setup

# Name of the big-bear-homebridge application
name: big-bear-homebridge
# Service definitions for the big-bear-homebridge application
services:
  # Service name: big-bear-homebridge
  # The `big-bear-homebridge` service definition
  big-bear-homebridge:
    # Name of the container
    container_name: big-bear-homebridge
    # Image to be used for the container
    image: homebridge/homebridge:2024-05-02
    # Container restart policy
    restart: unless-stopped
    # Environment Variables
    environment:
      - TZ=UTC # Timezone
    privileged: true
    network_mode: host
    # Volumes HOST:CONTAINER
    volumes:
      - homebridge_data:/homebridge
volumes:
  homebridge_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: homebridge
    description: HomeBridge
    useHost: true
    target: http://localhost:8581
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
