cosmos-installer: null
name: big-bear-homebridge
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: homebridge/homebridge:2024-05-02
    restart: unless-stopped
    environment:
      - TZ=UTC
    privileged: true
    network_mode: host
    volumes:
      - "{ServiceName}-data:/homebridge"
    hostname: "{ServiceName}"
minVersion: 0.14.0
