cosmos-installer: null
services:
  app:
    image: linuxserver/pelorus:0.2.3@sha256:2ce1c2b9b6add922a6592cafae11481b988d3a5dc6bb7ed0634ec31db2f0bc0a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pelorus/config
        target: /config
minVersion: 0.14.0
