cosmos-installer: null
services:
  app:
    image: linuxserver/sealskin:0.3.2@sha256:25d6fae59c5dda6e2640aba444cad515876c2ba919ad0be7ba94ddf3282ef914
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HOST_URL: ''
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/sealskin/config
        target: /config
      - type: bind
        source: /DATA/AppData/sealskin/storage
        target: /storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
minVersion: 0.14.0
