# Configuration for sftpgo setup

# Name of the big-bear-sftpgo application
name: big-bear-sftpgo
# Service definitions for the big-bear-sftpgo application
services:
  # Service name: app
  # The `app` service definition
  big-bear-sftpgo:
    # Name of the container
    container_name: big-bear-sftpgo
    # Image to be used for the container
    image: drakkan/sftpgo:v2.7
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      - sftpgo_srv:/srv/sftpgo
      - sftpgo_data:/var/lib/sftpgo
    # Ports mapping between host and container
    ports:
      # Mapping port 7575 of the host to port 7575 of the container
      - "8080:8080"
      - "2022:2022"
      - "2121:2121"
      - "10080:10080"
    environment:
      - SFTPGO_HTTPD_BINDINGS_0_PORT=8080
      - SFTPGO_HTTPD_BINDINGS_0_ADDRESS=0.0.0.0
      - SFTPGO_DATA_PROVIDER_CREATE_DEFAULT_ADMIN=true
      - SFTPGO_WEBDAVD_BINDINGS_0_PORT=10080
      - SFTPGO_FTPD_BINDINGS_0_PORT=2121
      - SFTPGO_FTPD_BINDINGS_0_FORCE_PASSIVE_IP='127.0.0.1:8080'
volumes:
  sftpgo_srv: {}
  sftpgo_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: sftpgo
    description: SFTPGO
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
