# Configuration for big-bear-minio setup
name: big-bear-minio
# Service definitions for the big-bear-minio application
services:
  # Service name: app
  app:
    image: bigbeartechworld/big-bear-minio:RELEASE.2025-10-15T17-29-55Z # The Docker image to use (latest version of minio)
    container_name: big-bear-minio # Name of the container instance
    volumes:
      - minio_data:/data # Mounting the project directory inside the container
    ports:
      - "9010:9000" # Expose minio's port 9000 on the host's port 9010
      - "9011:9001" # Expose minio web console's port 9001 on the host's port 9011
    environment:
      MINIO_ROOT_PASSWORD: "minioadmin"
      MINIO_ROOT_USER: "minioadmin"
    restart: unless-stopped # Policy to restart the container if it stops unexpectedly
    command: ["server", "--console-address", ":9001", "/data"]
volumes:
  minio_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: minio
    description: Minio
    useHost: true
    target: http://localhost:9011
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
