# Name of the configuration: big-bear-flcontainers-guacamole
name: big-bear-flcontainers-guacamole
# Define the services required for the application
services:
  # app service configuration
  app:
    # Docker image to use for this service
    image: flcontainers/guacamole:1.6.0
    # Container name
    container_name: big-bear-flcontainers-guacamole
    # Restart policy for the container
    restart: always
    # Environment variables for the app service
    environment:
      tz: "UTC"
      EXTENSIONS: "auth-totp,auth-ldap"
    # Map port 8080 on the host to port 8080 on the container
    ports:
      - 8080:8080

# Cosmos-specific routes for reverse proxy
routes:
  - name: flcontainers-guacamole
    description: FlContainers Guacamole
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
