# Configuration for tailscale setup

# Name of the big-bear-tailscale application
name: big-bear-tailscale
# Service definitions for the big-bear-tailscale application
services:
  # Service name: big-bear-tailscale
  # The `big-bear-tailscale` service definition
  big-bear-tailscale:
    # Name of the container
    container_name: big-bear-tailscale
    # Image to be used for the container
    image: tailscale/tailscale:v1.88.4
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      - TS_SERVE_CONFIG=""
      - TS_ACCEPT_DNS=false
      - TS_AUTH_ONCE=false
      - TS_AUTHKEY=""
      - TS_HOSTNAME=""
      - TS_ROUTES=""
      - TS_EXTRA_ARGS=""
      - TS_USERSPACE=true
      - TS_STATE_DIR=/var/lib/tailscale
    # Volumes to be mounted to the container
    volumes:
      - tailscale_state:/var/lib/tailscale
      - tailscale_config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
volumes:
  tailscale_state: {}
  tailscale_config: {}
