cosmos-installer: null
services:
  app:
    image: linuxserver/ungoogled-chromium:153.0.8010@sha256:d7d68f4848e2d5b2b9d553111e9ac08ee44433622a8692338659ce52d0368e66
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ungoogled-chromium/config
        target: /config
minVersion: 0.14.0
