# Configuration for appsmith setup

# Name of the big-bear-appsmith application
name: big-bear-appsmith
# Service definitions for the big-bear-appsmith application
services:
  # Service name: app
  # The `app` service definition
  app:
    image: appsmith/appsmith-ce:v1.73.1 # Docker image to use
    container_name: appsmith # Name of the container
    ports:
      - "1080:80" # Port mapping host:container for HTTP
      - "10443:443" # Port mapping host:container for HTTPS
    volumes:
      - appsmith_stacks:/appsmith-stacks # Mount volume for app data
    restart: unless-stopped # Container restart policy
volumes:
  appsmith_stacks: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: appsmith
    description: Appsmith
    useHost: true
    target: http://localhost:1080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
