# Configuration for big-bear-wordpress setup

# Name of the big-bear-wordpress application
name: big-bear-wordpress
# Service definitions for the wordpress application
services:
  # Service definition for the main application
  app:
    # Docker image to use for the application
    image: wordpress:6.8.3
    # Port mapping for the application
    ports:
      - 8080:80
    # Environment variables for the application
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: casaos
      WORDPRESS_DB_PASSWORD: casaos
      WORDPRESS_DB_NAME: wordpress
    # Volume mapping for the application
    volumes:
      - wordpress_html:/var/www/html
    # Service dependencies for the application
    depends_on:
      - db
  # Service definition for the database
  db:
    # Docker image to use for the database
    image: mysql:5.7
    # Environment variables for the database
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: casaos
      MYSQL_PASSWORD: casaos
      MYSQL_ROOT_PASSWORD: casaos
    # Volume mapping for the database
    volumes:
      - wordpress_mysql:/var/lib/mysql
volumes:
  wordpress_html: {}
  wordpress_mysql: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: wordpress
    description: WordPress
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
