cosmos-installer: null
name: big-bear-faster-whisper
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: linuxserver/faster-whisper:2.5.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WHISPER_MODEL=tiny-int8
      - WHISPER_BEAM=1
      - WHISPER_LANG=en
    volumes:
      - "{ServiceName}-data:/config"
    ports:
      - 10300:10300
    hostname: "{ServiceName}"
minVersion: 0.14.0
