cosmos-installer: null
services:
  app:
    image: linuxserver/grav:2.2.5@sha256:77135750827ca26b4969938ee5de30db821ba3d7cb9d3f80f0af4f1b57cc7133
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
minVersion: 0.14.0
