cosmos-installer: null
services:
  app:
    image: linuxserver/grav:2.2.4@sha256:7eb1a043e5c7ec95203eb4fdcd63294fb15ece82297dfeae0ec32cfa1664570b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
minVersion: 0.14.0
