cosmos-installer: null
services:
  app:
    image: linuxserver/grav:2.1.8@sha256:20c3eb58ad9e2250cb0f836e202ff7e4b01efca97f4f344baa2a50c87ac4dc81
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
minVersion: 0.14.0
