cosmos-installer: null
services:
  app:
    image: linuxserver/grocy:4.7.1@sha256:c0d0d9d22d3a54fe3f779a743baa2d7bab96b73fad5597ff1a631e2be4b863c8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 9283
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grocy/config
        target: /config
minVersion: 0.14.0
