cosmos-installer: null
services:
  app:
    image: linuxserver/retroarch:1.22.2@sha256:9c49f83df056635e8dd52ea9838e6d7490da36b45325a9913fd08cc79c678b2c
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
minVersion: 0.14.0
