cosmos-installer: null
services:
  app:
    image: linuxserver/msedge:154.0.4258@sha256:40a91a1bfd1d9e06636e30ddd2c89edb4c1101e905d252266b9a174e0465f1da
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EDGE_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/msedge/config
        target: /config
minVersion: 0.14.0
