# Configuration for calcom setup

# Name of the big-bear-calcom application
name: big-bear-calcom
# Service definitions for the big-bear-calcom application
services:
  # Service name: big-bear-calcom
  # The `big-bear-calcom` service definition
  big-bear-calcom:
    # Name of the container
    container_name: big-bear-calcom
    # Image to be used for the container
    image: calcom/cal.com:v5.8.2
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - DATABASE_HOST=big-bear-calcom-db
      - DATABASE_URL=postgresql://bigbear:9e45944b-37bb-41f7-aa6f-b74195fb58ec@big-bear-calcom-db/bigbear_calcom
      - DATABASE_DIRECT_URL=postgresql://bigbear:9e45944b-37bb-41f7-aa6f-b74195fb58ec@big-bear-calcom-db/bigbear_calcom
      - POSTGRES_USER=bigbear
      - POSTGRES_PASSWORD=9e45944b-37bb-41f7-aa6f-b74195fb58ec
      - POSTGRES_DB=bigbear_calcom
      - LICENSE=agree
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - NEXT_PUBLIC_WEBAPP_URL=http://localhost:3000
      - NEXTAUTH_SECRET=a5446147-f55c-4e29-98e7-e7638f223b9c
      - CALENDSO_ENCRYPTION_KEY=82f83d51-5ef7-456c-8ebf-817495cd39d9
      - MS_GRAPH_CLIENT_ID=
      - MS_GRAPH_CLIENT_SECRET=
      - ZOOM_CLIENT_ID=
      - ZOOM_CLIENT_SECRET=
      - GOOGLE_API_CREDENTIALS=
      - EMAIL_FROM=user@example.com
      - EMAIL_SERVER_HOST=mailpit
      - EMAIL_SERVER_PORT=1025
      - EMAIL_SERVER_PASSWORD=
      - EMAIL_SERVER_USER=
      - NODE_ENV=production
    # Volumes to be mounted to the container
    volumes:
      - calcom_config:/config
    # Ports mapping between host and container
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - big_bear_calcom_network
  big-bear-calcom-db:
    container_name: big-bear-calcom-db
    image: postgres:16.1
    restart: on-failure
    volumes:
      - calcom_data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=9e45944b-37bb-41f7-aa6f-b74195fb58ec
      - POSTGRES_USER=bigbear
      - POSTGRES_DB=bigbear_calcom
    networks:
      - big_bear_calcom_network
networks:
  big_bear_calcom_network:
    driver: bridge
volumes:
  calcom_config: {}
  calcom_data_db: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: calcom
    description: Cal.com
    useHost: true
    target: http://localhost:3000
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
