cosmos-installer: null
services:
  app:
    image: linuxserver/rsnapshot:1.4.5@sha256:92547730d7276ec5b2748bdc3f26bad6b05ba7c6413da41bf865fb931d30c2f9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
minVersion: 0.14.0
