cosmos-installer: null
services:
  app:
    image: linuxserver/rsnapshot:1.4.5@sha256:40b42ceaf1ca02e4a598de0ee6b862dca3d4c8bb85aaad969b21529f034542e0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/rsnapshot/config
        target: /config
      - type: bind
        source: /DATA/AppData/rsnapshot/.snapshots
        target: /.snapshots
      - type: bind
        source: /DATA/AppData/rsnapshot/data
        target: /data
minVersion: 0.14.0
