cosmos-installer: null
services:
  app:
    image: linuxserver/xemu:0.8.134@sha256:b3e18555f3d762faf989d5cd84508328bc38c66f1086f00062482b336e244424
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
minVersion: 0.14.0
