cosmos-installer: null
services:
  app:
    image: linuxserver/xemu:0.8.134@sha256:9ef505ebf120e427deab5bf5da2d7e91616ae9da7fc0dc09bc741a01dea1e732
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
minVersion: 0.14.0
