cosmos-installer: null
services:
  app:
    image: linuxserver/xemu:0.8.134@sha256:58479147a958912ed943857edf95f54e7b57f4cedff6b2863b30349ce36bcd85
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
minVersion: 0.14.0
