cosmos-installer: null
services:
  app:
    image: linuxserver/citron:2026.02.1@sha256:6d955bd6dce826c40f3ffdb793c4711826179cf411c2f72c4c27358413195ddb
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /srv/lsio/citron/config
        target: /config
minVersion: 0.14.0
