cosmos-installer: null
name: big-bear-odoo
services:
  "{ServiceName}-big-bear-odoo":
    container_name: "{ServiceName}-big-bear-odoo"
    image: odoo:18
    restart: unless-stopped
    user: root
    volumes:
      - "{ServiceName}-big-bear-odoo-data:/etc/odoo"
      - "{ServiceName}-big-bear-odoo-data-2:/mnt/extra-addons"
    ports:
      - 8069:8069
    environment:
      - HOST=big-bear-odoo-db
      - USER=odoo
      - PASSWORD=a8d785b6-bc00-49cc-8675-d404093d1507
    networks:
      - big_bear_odoo_network
    hostname: "{ServiceName}-big-bear-odoo"
  "{ServiceName}-big-bear-odoo-db":
    container_name: "{ServiceName}-big-bear-odoo-db"
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=a8d785b6-bc00-49cc-8675-d404093d1507
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-odoo-db-data:/var/lib/postgresql/data"
    networks:
      - big_bear_odoo_network
    hostname: "{ServiceName}-big-bear-odoo-db"
networks:
  big_bear_odoo_network:
    driver: bridge
minVersion: 0.14.0
