cosmos-installer: null
services:
  app:
    image: linuxserver/intellij-idea:42026.2.3@sha256:fd989215cf489a15237096a100df8eeeb7e3b0224c398ac76346bb35b0908da2
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/intellij-idea/config
        target: /config
minVersion: 0.14.0
