cosmos-installer: null
services:
  app:
    image: linuxserver/intellij-idea:42026.2.2@sha256:0bcb707fd86f9238abed6a531ba88d6776dbf8ccdc75bdaa38c571e71bce876e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/intellij-idea/config
        target: /config
minVersion: 0.14.0
