cosmos-installer: null
services:
  app:
    image: linuxserver/winegui:4.5.0@sha256:4307fa122059e94d3f37841b9406cfcf3c76029656411ce93487a3c0e6540360
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/winegui/config
        target: /config
minVersion: 0.14.0
