cosmos-installer: null
name: big-bear-farmos
services:
  "{ServiceName}-big-bear-farmos":
    container_name: "{ServiceName}-big-bear-farmos"
    image: farmos/farmos:3.4.4
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-farmos-data:/opt/drupal/web/sites"
    ports:
      - 8080:80
    networks:
      - big-bear-farmos-network
    hostname: "{ServiceName}-big-bear-farmos"
  "{ServiceName}-big-bear-farmos-db":
    container_name: "{ServiceName}-big-bear-farmos-db"
    image: mariadb:10
    volumes:
      - "{ServiceName}-big-bear-farmos-db-data:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 037ed96f-5f27-4fa8-bd7f-49b4a804a05c
      MYSQL_DATABASE: big_bear_farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: 037ed96f-5f27-4fa8-bd7f-49b4a804a05c
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    networks:
      - big-bear-farmos-network
    hostname: "{ServiceName}-big-bear-farmos-db"
networks:
  big-bear-farmos-network:
    name: big-bear-farmos-network
    driver: bridge
minVersion: 0.14.0
