cosmos-installer: null
name: big-bear-stirling-pdf
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: stirlingtools/stirling-pdf:0.37.1
    restart: unless-stopped
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLE_LOGIN=true
      - SECURITY_INITIALLOGIN_USERNAME=bigbear
      - SECURITY_INITIALLOGIN_PASSWORD=4500733e-a0f8-4605-a712-fd267404956a
      - CSRF_DISABLED=false
      - DEFAULT_LOCALE=en-US
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    volumes:
      - "{ServiceName}-data:/usr/share/tessdata"
      - "{ServiceName}-data-2:/configs"
    ports:
      - 8080:8080
    hostname: "{ServiceName}"
minVersion: 0.14.0
