cosmos-installer: null
name: big-bear-pingvin-share
services:
  "{ServiceName}":
    image: stonith404/pingvin-share:v1.11.1
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - "{ServiceName}-data:/opt/app/backend/data"
      - "{ServiceName}-data-2:/opt/app/frontend/public/img"
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
