cosmos-installer: null
services:
  app:
    image: linuxserver/vscodium:1.135.06055@sha256:3a30e9ea4702b685ee6e4e884b9e785442b0db1d2e567c6f271799b1bd83827b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/vscodium/config
        target: /config
minVersion: 0.14.0
