cosmos-installer: null
services:
  app:
    image: linuxserver/cura:5.13.0@sha256:fd98df9f9ac514f63e900dafb38d165b22d3c2918d61e72bb9526f9d676c59d7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
minVersion: 0.14.0
