cosmos-installer: null
services:
  app:
    image: linuxserver/cura:5.13.0@sha256:a5cbd23c61bf7db73a02e5e4ddf4926320ae6120735bb87d18bc74bfb67c0025
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
minVersion: 0.14.0
