cosmos-installer: null
name: big-bear-upsnap
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/seriousm4x/upsnap:5.1.6
    restart: unless-stopped
    network_mode: host
    volumes:
      - "{ServiceName}-data:/app/pb_data"
    hostname: "{ServiceName}"
minVersion: 0.14.0
