cosmos-installer: null
services:
  app:
    image: linuxserver/filezilla:3.69.6@sha256:c74d8e56d7a48d7e643e06f4f8119790df0eacbb0340268323704d349c94231f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/filezilla/config
        target: /config
minVersion: 0.14.0
