cosmos-installer: null
services:
  app:
    image: linuxserver/filezilla:3.69.6@sha256:0115048da2837b65e16de32d2d786bac27ceea15ca7dcc5cd3108fc5c9c74085
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/filezilla/config
        target: /config
minVersion: 0.14.0
