cosmos-installer: null
name: big-bear-coolify
services:
  "{ServiceName}-big-bear-coolify":
    container_name: "{ServiceName}-big-bear-coolify"
    image: ghcr.io/coollabsio/coolify:4.0.0-beta.380
    restart: unless-stopped
    environment:
      - PHP_MEMORY_LIMIT="512M"
      - APP_ID="coolify"
      - APP_ENV="production"
      - APP_DEBUG="false"
      - APP_NAME="Coolify"
      - APP_KEY="base64:lSStPbXB/yW6cxXIz8fauQ937PbSUktTdIf7R05szQ4="
      - APP_URL="http://[CASAOS_IP]:8000"
      - DB_CONNECTION="pgsql"
      - DB_HOST={ServiceName}-"big-bear-coolify-postgres"
      - DB_PORT="5432"
      - DB_DATABASE="coolify"
      - DB_USERNAME="coolify"
      - DB_PASSWORD="f1986213-9d72-4c36-bbd4-adca2f414fa1"
      - QUEUE_CONNECTION="redis"
      - REDIS_HOST={ServiceName}-"big-bear-coolify-redis"
      - REDIS_PASSWORD="9e3df6aa-ea48-4e59-a9c4-59798f1ba9b4"
      - HORIZON_BALANCE="100"
      - HORIZON_MAX_PROCESSES="10"
      - HORIZON_BALANCE_MAX_SHIFT="10"
      - HORIZON_BALANCE_COOLDOWN="10"
      - SSL_MODE="off"
      - PHP_PM_CONTROL="dynamic"
      - PHP_PM_START_SERVERS="1"
      - PHP_PM_MIN_SPARE_SERVERS="1"
      - PHP_PM_MAX_SPARE_SERVERS="10"
      - PUSHER_HOST="big-bear-coolify-soketi"
      - PUSHER_BACKEND_HOST="big-bear-coolify-soketi"
      - PUSHER_PORT="6001"
      - PUSHER_BACKEND_PORT="6001"
      - PUSHER_SCHEME="http"
      - PUSHER_APP_ID="coolify"
      - PUSHER_APP_KEY=
      - PUSHER_APP_SECRET=
      - AUTOUPDATE=true
      - SELF_HOSTED=true
      - SSH_MUX_PERSIST_TIME=3600
      - FEEDBACK_DISCORD_WEBHOOK=
      - WAITLIST=
      - SUBSCRIPTION_PROVIDER=
      - STRIPE_API_KEY=
      - STRIPE_WEBHOOK_SECRET=
      - STRIPE_PRICE_ID_BASIC_MONTHLY=
      - STRIPE_PRICE_ID_BASIC_YEARLY=
      - STRIPE_PRICE_ID_PRO_MONTHLY=
      - STRIPE_PRICE_ID_PRO_YEARLY=
      - STRIPE_PRICE_ID_ULTIMATE_MONTHLY=
      - STRIPE_PRICE_ID_ULTIMATE_YEARLY=
      - STRIPE_PRICE_ID_DYNAMIC_MONTHLY=
      - STRIPE_PRICE_ID_DYNAMIC_YEARLY=
      - STRIPE_PRICE_ID_BASIC_MONTHLY_OLD=
      - STRIPE_PRICE_ID_BASIC_YEARLY_OLD=
      - STRIPE_PRICE_ID_PRO_MONTHLY_OLD=
      - STRIPE_PRICE_ID_PRO_YEARLY_OLD=
      - STRIPE_PRICE_ID_ULTIMATE_MONTHLY_OLD=
      - STRIPE_PRICE_ID_ULTIMATE_YEARLY_OLD=
      - STRIPE_EXCLUDED_PLANS=
    volumes:
      - "{ServiceName}-big-bear-coolify-data:/var/www/html/storage/app/ssh"
      - "{ServiceName}-big-bear-coolify-data-2:/var/www/html/storage/app/applic\
        ations"
      - "{ServiceName}-big-bear-coolify-data-3:/var/www/html/storage/app/databa\
        ses"
      - "{ServiceName}-big-bear-coolify-data-4:/var/www/html/storage/app/servic\
        es"
      - "{ServiceName}-big-bear-coolify-data-5:/var/www/html/storage/app/backups"
      - "{ServiceName}-big-bear-coolify-data-6:/var/www/html/storage/app/webhoo\
        ks-during-maintenance"
      - "{ServiceName}-big-bear-coolify-data-7:/var/www/html/storage/logs"
    ports:
      - 8000:80
    healthcheck:
      test: curl --fail http://127.0.0.1:80/api/health || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      - "{ServiceName}-big-bear-coolify-postgres"
      - "{ServiceName}-big-bear-coolify-redis"
    networks:
      - big_bear_coolify_network
    hostname: "{ServiceName}-big-bear-coolify"
  "{ServiceName}-big-bear-coolify-postgres":
    container_name: "{ServiceName}-big-bear-coolify-postgres"
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - "{ServiceName}-big-bear-coolify-postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: f1986213-9d72-4c36-bbd4-adca2f414fa1
      POSTGRES_DB: coolify
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U coolify
        - -d
        - coolify
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - big_bear_coolify_network
    hostname: "{ServiceName}-big-bear-coolify-postgres"
  "{ServiceName}-big-bear-coolify-redis":
    container_name: "{ServiceName}-big-bear-coolify-redis"
    image: redis:alpine
    ports:
      - 6379:6379
    command:
      - redis-server
      - --save
      - "20"
      - "1"
      - --loglevel
      - warning
      - --requirepass
      - 9e3df6aa-ea48-4e59-a9c4-59798f1ba9b4
    environment:
      REDIS_PASSWORD: 9e3df6aa-ea48-4e59-a9c4-59798f1ba9b4
    volumes:
      - "{ServiceName}-big-bear-coolify-redis-data:/data"
    healthcheck:
      test: redis-cli ping
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - big_bear_coolify_network
    hostname: "{ServiceName}-big-bear-coolify-redis"
  "{ServiceName}-big-bear-coolify-soketi":
    container_name: "{ServiceName}-big-bear-coolify-soketi"
    image: quay.io/soketi/soketi:1.6-16-alpine
    ports:
      - 6001:6001
      - 6002:6002
    environment:
      SOKETI_DEBUG: "false"
      SOKETI_DEFAULT_APP_ID: ""
      SOKETI_DEFAULT_APP_KEY: ""
      SOKETI_DEFAULT_APP_SECRET: ""
    healthcheck:
      test: wget -qO- http://127.0.0.1:6001/ready || exit 1
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - big_bear_coolify_network
    hostname: "{ServiceName}-big-bear-coolify-soketi"
networks:
  big_bear_coolify_network:
    name: big_bear_coolify_network
    driver: bridge
  coolify:
    external: true
minVersion: 0.14.0
