# Configuration for pihole setup

# Name of the big-bear-pihole application
name: big-bear-pihole
# Service definitions for the big-bear-pihole application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-pihole
    # Image to be used for the container
    image: pihole/pihole:2025.08.0
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      TZ: "UTC"
      FTLCONF_webserver_api_password: "your_password"
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/etc directory to /etc/pihole/ inside the container
      - pihole_etc:/etc/pihole/
      # Mounting the local /DATA/AppData/$AppID/dnsmasq.d directory to /etc/dnsmasq.d inside the container
      - pihole_dnsmasq.d:/etc/dnsmasq.d/
    # Ports mapping between host and container
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "10443:443/tcp"
    # Define the networks section
    networks:
      # Define the pihole-network
      - pihole-network
# Define the networks section
networks:
  # Define the pihole-network
  pihole-network:
    # Set the driver to bridge
    driver: bridge
volumes:
  pihole_etc: {}
  pihole_dnsmasq.d: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: pihole
    description: Pi-hole
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
