# Configuration for homarr setup

# Name of the big-bear-homarr application
name: big-bear-homarr
# Service definitions for the big-bear-homarr application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: homarr
    # Image to be used for the container
    image: ghcr.io/ajnart/homarr:0.16.0
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local homarr/configs directory to /app/data/configs inside the container
      - homarr_configs:/app/data/configs
      # Mounting the local homarr/icons directory to /app/public/icons inside the container
      - homarr_icons:/app/public/icons
      # Mounting the local homarr/dat directory to /data inside the container
      - homarr_data:/data
      # Mounting docker.sock to allow docker management via Homarr
      - /var/run/docker.sock:/var/run/docker.sock
    # Ports mapping between host and container
    ports:
      # Mapping port 7575 of the host to port 7575 of the container
      - "7575:7575"
volumes:
  homarr_configs: {}
  homarr_icons: {}
  homarr_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: homarr
    description: Homarr
    useHost: true
    target: http://localhost:7575
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
