cosmos-installer: null
name: big-bear-portainer-agent
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: portainer/agent:2.19.4
    network_mode: bridge
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    hostname: "{ServiceName}"
minVersion: 0.14.0
