cosmos-installer: null
services:
  app:
    image: linuxserver/helium:0.18.3@sha256:342fbaa7048b733b94bf94b4572d7c3b746c16bc3073e0403a80c77f1429f3c4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HELIUM_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/helium/config
        target: /config
minVersion: 0.14.0
