cosmos-installer: null
services:
  app:
    image: linuxserver/foldingathome:8.5.6@sha256:6245b3f602f8a3b95653d640d24342eed40234d0723d260d8fc3bedd55d00fc6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ACCOUNT_TOKEN: ''
      MACHINE_NAME: ''
      CLI_ARGS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 7396
        published: 7396
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/foldingathome/config
        target: /config
minVersion: 0.14.0
