cosmos-installer: null
services:
  app:
    image: linuxserver/znc:1.10.3@sha256:51e139085d594ca3b90c415ef081fee2a394387668acb54d32cc9c2852a33823
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6501
        published: 6501
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/znc/config
        target: /config
minVersion: 0.14.0
