cosmos-installer: null
services:
  app:
    image: linuxserver/d2-builder:0.9.0@sha256:a6a6c3f337c0801b29bd8897bca9da75d1c9ac716929628546eafb571558a256
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/d2-builder/config
        target: /config
minVersion: 0.14.0
