cosmos-installer: null
services:
  app:
    image: linuxserver/d2-builder:0.9.0@sha256:f2a3c7f4f14050bc50665d240b2bbab49b037dbc0fe63b46385287674dcff662
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/d2-builder/config
        target: /config
minVersion: 0.14.0
