cosmos-installer: null
name: big-bear-gladys
services:
  "{ServiceName}":
    image: gladysassistant/gladys:v4.61.0
    restart: always
    privileged: true
    network_mode: host
    container_name: "{ServiceName}"
    cgroup: host
    environment:
      NODE_ENV: production
      SQLITE_FILE_PATH: /var/lib/gladysassistant/gladys-production.db
      TZ: Europe/Paris
      SERVER_PORT: "1080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{ServiceName}-data:/var/lib/gladysassistant"
      - /dev:/dev
      - /run/udev:/run/udev
    hostname: "{ServiceName}"
minVersion: 0.14.0
