cosmos-installer: null
name: big-bear-owncloud
services:
  "{ServiceName}-big-bear-owncloud":
    container_name: "{ServiceName}-big-bear-owncloud"
    image: owncloud/server:10.15.3
    restart: unless-stopped
    environment:
      - OWNCLOUD_DOMAIN=http://[YOUR_CASAOS_IP]:8080
      - OWNCLOUD_TRUSTED_DOMAINS=[YOUR_CASAOS_IP]
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=big_bear_owncloud
      - OWNCLOUD_DB_USERNAME=bigbear
      - OWNCLOUD_DB_PASSWORD=f01914eb-2be3-4164-a57c-08e6518f313a
      - OWNCLOUD_DB_HOST=big-bear-owncloud-db
      - OWNCLOUD_ADMIN_USERNAME=bigbear
      - OWNCLOUD_ADMIN_PASSWORD=ed135299-7c80-48d4-a2a0-357a012213e5
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=big-bear-owncloud-redis
    volumes:
      - "{ServiceName}-big-bear-owncloud-data:/mnt/data"
    ports:
      - 8080:8080
    networks:
      - big_bear_owncloud_network
    healthcheck:
      test:
        - CMD
        - /usr/bin/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - "{ServiceName}-big-bear-owncloud-db"
      - "{ServiceName}-big-bear-owncloud-redis"
    hostname: "{ServiceName}-big-bear-owncloud"
  "{ServiceName}-big-bear-owncloud-db":
    container_name: "{ServiceName}-big-bear-owncloud-db"
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=f01914eb-2be3-4164-a57c-08e6518f313a
      - MYSQL_USER=bigbear
      - MYSQL_PASSWORD=f01914eb-2be3-4164-a57c-08e6518f313a
      - MYSQL_DATABASE=big_bear_owncloud
      - MARIADB_AUTO_UPGRADE=1
    command:
      - --max-allowed-packet=128M
      - --innodb-log-file-size=64M
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -u
        - bigbear
        - --password=f01914eb-2be3-4164-a57c-08e6518f313a
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "{ServiceName}-big-bear-owncloud-db-data:/var/lib/mysql"
    networks:
      - big_bear_owncloud_network
    hostname: "{ServiceName}-big-bear-owncloud-db"
  "{ServiceName}-big-bear-owncloud-redis":
    container_name: "{ServiceName}-big-bear-owncloud-redis"
    image: redis:6
    restart: unless-stopped
    command:
      - --databases
      - "1"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "{ServiceName}-big-bear-owncloud-redis-data:/data"
    networks:
      - big_bear_owncloud_network
    hostname: "{ServiceName}-big-bear-owncloud-redis"
networks:
  big_bear_owncloud_network:
    name: big_bear_owncloud_network
    driver: bridge
minVersion: 0.14.0
