cosmos-installer: null
name: big-bear-zipline
services:
  "{ServiceName}-zipline":
    container_name: "{ServiceName}-zipline"
    image: ghcr.io/diced/zipline:3.7.8
    restart: unless-stopped
    volumes:
      - "{DefaultDataPath}/AppData/{ServiceName}/uploads:/zipline/uploads"
      - "{DefaultDataPath}/AppData/{ServiceName}/public:/zipline/public"
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=changeme
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://postgres:postgrespassword@zipline-db/zipline
      - CORE_LOGGER=true
    ports:
      - 3000:3000
    networks:
      - zipline_network
    hostname: "{ServiceName}-zipline"
  "{ServiceName}-zipline-db":
    container_name: "{ServiceName}-zipline-db"
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DATABASE=zipline
    volumes:
      - "{DefaultDataPath}/AppData/{ServiceName}/postgres:/var/lib/postgresql/d\
        ata"
    networks:
      - zipline_network
    hostname: "{ServiceName}-zipline-db"
networks:
  zipline_network:
    driver: bridge
minVersion: 0.14.0-0
