# Configuration for home-assistant setup

# Name of the big-bear-home-assistant application
name: big-bear-home-assistant
# Service definitions for the big-bear-home-assistant application
services:
  # Service name: app
  # The `app` service definition
  app:
    # Name of the container
    container_name: big-bear-home-assistant
    # Image to be used for the container
    image: ghcr.io/home-assistant/home-assistant:2025.10.4
    # Container restart policy
    restart: unless-stopped
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/$AppID/config directory to /config inside the container
      - home_assistant_config:/config
      # Mounting the local /etc/localtime to /etc/localtime inside the container
      - /etc/localtime:/etc/localtime:ro
      # Mounting the local /run/dbus to /run/dbus inside the container
      - /run/dbus:/run/dbus:ro
    # Network mode for the container
    network_mode: host
volumes:
  home_assistant_config: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: home-assistant
    description: Home Assistant
    useHost: true
    target: http://localhost:8123
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
