cosmos-installer: null
name: big-bear-home-assistant
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/home-assistant/home-assistant:2024.3.3
    restart: unless-stopped
    volumes:
      - "{ServiceName}-data:/config"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    network_mode: host
    hostname: "{ServiceName}"
minVersion: 0.14.0
