cosmos-installer: null
services:
  app:
    image: linuxserver/webstation:0.14.0-romm@sha256:bc8d534ab9fa512f33cf3b86d65b64df3e5126db5963f41c0a5fa97a2654e6db
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webstation/config
        target: /config
minVersion: 0.14.0
