cosmos-installer: null
services:
  app:
    image: linuxserver/webstation:0.13.0-romm@sha256:97000f8ca20a459651ed664c0d03449814917e0f3ad96d9f4bf276ad4fe322a9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webstation/config
        target: /config
minVersion: 0.14.0
