cosmos-installer: null
name: big-bear-immich
services:
  "{ServiceName}-immich-server":
    container_name: "{ServiceName}-immich-server"
    image: ghcr.io/immich-app/immich-server:v1.125.5
    ports:
      - 2283:2283
    volumes:
      - "{ServiceName}-immich-server-data:/usr/src/app/upload"
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: immich
      DB_PORT: "5432"
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on:
      - "{ServiceName}-redis"
      - "{ServiceName}-database"
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-immich-server"
  "{ServiceName}-immich-machine-learning":
    container_name: "{ServiceName}-immich-machine-learning"
    image: ghcr.io/immich-app/immich-machine-learning:v1.125.5
    volumes:
      - "{ServiceName}-immich-machine-learning-data:/cache"
    environment:
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: casaos
      DB_DATABASE_NAME: casaos
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-immich-machine-learning"
  "{ServiceName}-redis":
    container_name: "{ServiceName}-redis"
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-redis"
  "{ServiceName}-database":
    container_name: "{ServiceName}-database"
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: casaos
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - "{ServiceName}-database-data:/var/lib/postgresql/data"
    restart: unless-stopped
    networks:
      - big_bear_immich_network
    hostname: "{ServiceName}-database"
networks:
  big_bear_immich_network:
    driver: bridge
minVersion: 0.14.0
