cosmos-installer: null
name: big-bear-flame
services:
  "{ServiceName}":
    image: pawelmalak/flame:multiarch2.3.1
    environment:
      PASSWORD: casaos
    restart: unless-stopped
    ports:
      - 5005:5005/tcp
    volumes:
      - type: volume
        source: "{ServiceName}-data"
        target: /app/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
minVersion: 0.14.0
