cosmos-installer: null
services:
  app:
    image: linuxserver/heimdall:2.8.3@sha256:4c2b77d7e391ac794ee7504839ed699a7f98309f853670ee45a7712a14c41001
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      ALLOW_INTERNAL_REQUESTS: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/heimdall/config
        target: /config
minVersion: 0.14.0
