cosmos-installer: null
services:
  app:
    image: linuxserver/hishtory-server:0.335.20260925@sha256:4acaa42e2501ec386037162261bbf68455dfe753644b6ed6801cf284de91e6ae
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      HISHTORY_POSTGRES_DB: ''
      HISHTORY_SQLITE_DB: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/hishtory-server/config
        target: /config
minVersion: 0.14.0
