cosmos-installer: null
name: big-bear-libredesk
services:
  "{ServiceName}-big-bear-libredesk":
    container_name: "{ServiceName}-big-bear-libredesk"
    image: libredesk/libredesk:v0.7.3-alpha
    restart: unless-stopped
    environment:
      - LIBREDESK_SYSTEM_USER_PASSWORD="c6b51a4e-ab9d-4f4f-933e-e96ed3570c1A"
    volumes:
      - "{ServiceName}-big-bear-libredesk-data:/libredesk/uploads"
      - "{ServiceName}-big-bear-libredesk-data-2:/libredesk/config"
    ports:
      - 9000:9000
    command:
      - sh
      - -c
      - ./libredesk --install --idempotent-install --yes --config
        /libredesk/config/config.toml && ./libredesk --upgrade --yes --config
        /libredesk/config/config.toml && ./libredesk --config
        /libredesk/config/config.toml
    depends_on:
      - "{ServiceName}-big-bear-libredesk-db"
      - "{ServiceName}-big-bear-libredesk-redis"
    networks:
      - big-bear-libredesk-network
    hostname: "{ServiceName}-big-bear-libredesk"
  "{ServiceName}-big-bear-libredesk-db":
    image: postgres:17-alpine
    container_name: "{ServiceName}-big-bear-libredesk-db"
    restart: unless-stopped
    networks:
      - big-bear-libredesk-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: libredesk
      POSTGRES_PASSWORD: libredesk
      POSTGRES_DB: big_bear_libredesk
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U libredesk
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
      - "{ServiceName}-big-bear-libredesk-db-data:/var/lib/postgresql/data"
    hostname: "{ServiceName}-big-bear-libredesk-db"
  "{ServiceName}-big-bear-libredesk-redis":
    image: redis:7-alpine
    container_name: "{ServiceName}-big-bear-libredesk-redis"
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - big-bear-libredesk-network
    volumes:
      - "{ServiceName}-big-bear-libredesk-redis-data:/data"
    hostname: "{ServiceName}-big-bear-libredesk-redis"
networks:
  big-bear-libredesk-network:
    driver: bridge
minVersion: 0.14.0
