# Configuration for big-bear-gotify setup
name: big-bear-gotify
# Service definitions for the big-bear-gotify application
services:
  # Service name: app
  app:
    image: gotify/server:2.7.3 # Docker image for the service
    ports:
      - 8091:80 # Port mapping (host:container)
    environment: # Environment variables for the service
      - GOTIFY_DEFAULTUSER_NAME=admin
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes: # Volume mapping (host:container)
      - "gotify_data:/app/data"
    network_mode: bridge # Network mode
volumes:
  gotify_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: gotify
    description: Gotify
    useHost: true
    target: http://localhost:8091
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
