cosmos-installer: null
services:
  app:
    image: linuxserver/kicad:10.0.3@sha256:c0da5a64426bbee5d0e95d325959518b7851f7a86ed89c35bc831fb7cc6996ae
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
minVersion: 0.14.0
