cosmos-installer: null
services:
  app:
    image: linuxserver/kicad:10.0.3@sha256:f75208310b82535435aba788a6443fb3ffd3f34ef68eae0b76a55ec2a18160f7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kicad/config
        target: /config
minVersion: 0.14.0
