# Configuration for wallos setup

# Name of the big-bear-wallos application
name: big-bear-wallos
# Service definitions for the big-bear-wallos application
services:
  # Service name: big-bear-wallos
  # The `big-bear-wallos` service definition
  big-bear-wallos:
    # Name of the container
    container_name: big-bear-wallos
    # Image to be used for the container
    image: bellamy/wallos:4.5.0
    # Container restart policy
    restart: unless-stopped
    # Environment variables for the container
    environment:
      TZ: "UTC" # Sets the time zone inside the container to Coordinated Universal Time (UTC).
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-wallos/db directory to /var/www/html/db inside the container
      - wallos_db:/var/www/html/db
      # Mounting the local /DATA/AppData/big-bear-wallos/logos directory to /var/www/html/images/uploads/logos inside the container
      - wallos_logos:/var/www/html/images/uploads/logos
    # Ports mapping between host and container
    ports:
      # Mapping port 8282 of the host to port 80 of the container
      - "8282:80"
volumes:
  wallos_db: {}
  wallos_logos: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: wallos
    description: Wallos
    useHost: true
    target: http://localhost:8282
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
