cosmos-installer: null
services:
  nova:
    image: mrantonsg/nova-dso-tracker:6.2.0@sha256:eb5cd12f4c7627ec6e70051f4bccc5852db1efcd349402929b0c2cc0da2f1938
    container_name: big-bear-nova-dso-tracker
    ports:
      - "5001:5001"
    volumes:
      - big-bear-nova-dso-tracker_data:/app/instance
    restart: unless-stopped
    network_mode: bridge
volumes:
  big-bear-nova-dso-tracker_data:
    name: big-bear-nova-dso-tracker_data
    driver: local
minVersion: 0.14.0
