cosmos-installer: null
services:
  app:
    image: linuxserver/dosbox-staging:0.83.0@sha256:7e2b4e639da689c3a005250ad9067e1beaa7c8c493a95a4034e58705bfe29bd4
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/dosbox-staging/config
        target: /config
minVersion: 0.14.0
