cosmos-installer: null
services:
  app:
    image: linuxserver/pydio-cells:5.1.0@sha256:fa339560b49539a9ca4872b94805444d0a66bd8755af4cb6978ea94f73652657
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      EXTERNALURL: ''
      SERVER_IP: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/pydio-cells/config
        target: /config
minVersion: 0.14.0
