cosmos-installer: null
name: big-bear-financial-freedom
services:
  "{ServiceName}-app":
    container_name: "{ServiceName}-app"
    image: serversideup/financial-freedom:v0.2.0-alpha1
    restart: unless-stopped
    networks:
      - financial-freedom-network
    volumes:
      - "{ServiceName}-app-data:/var/www/html/storage/logs"
      - "{ServiceName}-app-data-2:/var/www/html/storage/framework/sessions"
    ports:
      - 8080:80
      - 8443:443
    environment:
      - APP_NAME="Financial Freedom"
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://[CASAOS_IP]:8080
      - APP_KEY=base64:1234567890abcdefghijklmnopqrstuvwxyz
      - DB_ROOT_PASSWORD=cd876479-f30b-43f2-8714-e52e040c657a
      - DB_HOST=mariadb
      - DB_DATABASE=financialfreedom
      - DB_USERNAME=bigbear
      - DB_PASSWORD=cd876479-f30b-43f2-8714-e52e040c657a
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailpit
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=noreply@financialfreedom.dev.test
      - MAIL_FROM_NAME="${APP_NAME}"
      - SSL_MODE=mixed
      - AUTORUN_ENABLED=true
      - AUTORUN_LARAVEL_EVENT_CACHE=false
      - AUTORUN_LARAVEL_ROUTE_CACHE=false
      - AUTORUN_LARAVEL_STORAGE_LINK=false
      - AUTORUN_LARAVEL_VIEW_CACHE=false
      - FINANCIAL_FREEDOM_ALLOW_REGISTRATION=false
      - LOG_CHANNEL=stack
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_LIFETIME=120
      - SESSION_DRIVER=cookie
      - MYSQL_ROOT_PASSWORD="cd876479-f30b-43f2-8714-e52e040c657a"
      - MYSQL_DATABASE="financialfreedom"
      - MYSQL_USER="bigbear"
      - MYSQL_PASSWORD="cd876479-f30b-43f2-8714-e52e040c657a"
    hostname: "{ServiceName}-app"
  "{ServiceName}-mariadb":
    image: mariadb:10.11
    volumes:
      - "{ServiceName}-mariadb-data:/var/lib/mysql"
    networks:
      - financial-freedom-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=cd876479-f30b-43f2-8714-e52e040c657a
      - MYSQL_DATABASE=financialfreedom
      - MYSQL_USER=bigbear
      - MYSQL_PASSWORD=cd876479-f30b-43f2-8714-e52e040c657a
      - REMOTE_SQL=
    container_name: "{ServiceName}-mariadb"
    hostname: "{ServiceName}-mariadb"
networks:
  financial-freedom-network:
    driver: bridge
minVersion: 0.14.0
