cosmos-installer: null
services:
  app:
    image: linuxserver/blender:5.2.2@sha256:9216c77ab2bf38a758390f802c5777554df605c53456dbcad828509a27a8f28b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
minVersion: 0.14.0
