cosmos-installer: null
services:
  app:
    image: linuxserver/blender:5.2.2@sha256:d66c5758fb64316bcc88a3e779b2d544df5c1d8c320f8003444994906657f230
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/blender/config
        target: /config
minVersion: 0.14.0
