# Configuration for ollama-amd setup

# Name of the big-bear-ollama-amd application
name: big-bear-ollama-amd
# Service definitions for the big-bear-ollama-amd application
services:
  # Service name: big-bear-ollama-amd
  # The `big-bear-ollama-amd` service definition
  big-bear-ollama-amd:
    # Name of the container
    container_name: big-bear-ollama-amd
    # Image to be used for the container
    image: ollama/ollama:0.12.6-rocm
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      - PORT=11434
    # Volumes to be mounted to the container
    volumes:
      - ollama_amd_.ollama:/root/.ollama
    # Ports mapping between host and container
    ports:
      # Mapping port 11434 of the host to port 11434 of the container
      - "11434:11434"
    devices:
      # Attach GPU
      - /dev/kfd
      - /dev/dri
volumes:
  ollama_amd_.ollama: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: ollama-amd
    description: Ollama - AMD
    useHost: true
    target: http://localhost:11434
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
