cosmos-installer: null
services:
  app:
    image: linuxserver/telegram:7.2.9@sha256:5394e30aa1dc45da74288c3c5d11247a8bc3c66137bb130073a6778fbba0062d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/telegram/config
        target: /config
minVersion: 0.14.0
