cosmos-installer: null
name: big-bear-spacedrive
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/spacedriveapp/spacedrive/server:0.4.2
    restart: unless-stopped
    environment:
      - SD_AUTH=bigbear:casaos
    volumes:
      - "{ServiceName}-data:/var/spacedrive"
    ports:
      - 8080:8080
    hostname: "{ServiceName}"
minVersion: 0.14.0
