cosmos-installer: null
name: big-bear-davis
services:
  "{ServiceName}-big-bear-davis":
    container_name: "{ServiceName}-big-bear-davis"
    image: ghcr.io/tchapi/davis-standalone:5.0.2
    restart: unless-stopped
    environment:
      - APP_ENV=prod
      - DATABASE_DRIVER=mysql
      - DATABASE_URL=mysql://bigbear:0c9d2acc-d4f3-423c-8361-86f35cdd3eb2@big-bear-davis-mysql:3306/davis?serverVersion=10.6.10&charset=utf8mb4
      - MAILER_DSN=smtp://:@big-bear-davis-mailpit:1025
      - ADMIN_LOGIN=bigbear
      - ADMIN_PASSWORD=aa9405b8-426c-41a1-bbc6-2924d8ec7eb3
      - AUTH_REALM=
      - AUTH_METHOD=
      - CALDAV_ENABLED=
      - CARDDAV_ENABLED=
      - WEBDAV_ENABLED=
      - WEBDAV_TMP_DIR=
      - WEBDAV_PUBLIC_DIR=
      - WEBDAV_HOMES_DIR=
      - INVITE_FROM_ADDRESS=
      - APP_TIMEZONE=UTC
    ports:
      - 9000:9000
    networks:
      - big-bear-davis-network
    depends_on:
      - "{ServiceName}-big-bear-davis-mysql"
      - "{ServiceName}-big-bear-davis-mailpit"
    hostname: "{ServiceName}-big-bear-davis"
  "{ServiceName}-big-bear-davis-mailpit":
    container_name: "{ServiceName}-big-bear-davis-mailpit"
    image: axllent/mailpit:v1.23
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-davis-mailpit-data:/data"
    environment:
      - TZ=UTC
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - big-bear-davis-network
    hostname: "{ServiceName}-big-bear-davis-mailpit"
  "{ServiceName}-big-bear-davis-mysql":
    container_name: "{ServiceName}-big-bear-davis-mysql"
    image: mariadb:10.6.10
    environment:
      - MYSQL_ROOT_PASSWORD=0c9d2acc-d4f3-423c-8361-86f35cdd3eb2
      - MYSQL_DATABASE=davis
      - MYSQL_USER=bigbear
      - MYSQL_PASSWORD=0c9d2acc-d4f3-423c-8361-86f35cdd3eb2
    volumes:
      - "{ServiceName}-big-bear-davis-mysql-data:/var/lib/mysql"
    networks:
      - big-bear-davis-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 10s
      retries: 5
      timeout: 5s
    hostname: "{ServiceName}-big-bear-davis-mysql"
networks:
  big-bear-davis-network:
    driver: bridge
minVersion: 0.14.0
