# Configuration for big-bear-dashy setup

# Name of the big-bear-dashy application
name: big-bear-dashy
# Service definitions for the dashy application
services:
  # Service name: big-bear-dashy
  big-bear-dashy:
    # Image to be used for the app service
    image: lissy93/dashy:3.1.0
    # Name of the container
    container_name: big-bear-dashy
    # Uncomment below if you want to mount volumes
    volumes:
      - dashy_public:/app/public
    # Ports mapping
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Restart policy for the container
    restart: unless-stopped
    # Configure healthchecks for the service
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  dashy_public: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: dashy
    description: Dashy
    useHost: true
    target: http://localhost:4000
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
