cosmos-installer: null
name: big-bear-btop
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: bigbeartechworld/big-bear-btop:0.1.1
    restart: unless-stopped
    privileged: true
    environment:
      - GOTTY_AUTH_USER=bigbear
      - GOTTY_AUTH_PASS=password
      - GOTTY_AUTH_ENABLED=true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - "{ServiceName}-data:/root/.config/btop"
    ports:
      - 7681:7681
    hostname: "{ServiceName}"
minVersion: 0.14.0
