cosmos-installer: null
name: big-bear-piwigo
services:
  "{ServiceName}-big-bear-piwigo":
    container_name: "{ServiceName}-big-bear-piwigo"
    image: linuxserver/piwigo:15.5.0
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - "{ServiceName}-big-bear-piwigo-data:/config"
      - "{ServiceName}-big-bear-piwigo-data-2:/gallery"
    ports:
      - 8080:80
    networks:
      - big_bear_piwigo_network
    hostname: "{ServiceName}-big-bear-piwigo"
  "{ServiceName}-big-bear-piwigo-db":
    image: mariadb:10.6
    container_name: "{ServiceName}-big-bear-piwigo-db"
    environment:
      - MYSQL_ROOT_PASSWORD=3cf3f2c4-3415-4efe-b478-db7b6f0b9934
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=big_bear_piwigo
      - MYSQL_PASSWORD=358fac48-4beb-4027-9c11-840464aca400
    volumes:
      - "{ServiceName}-big-bear-piwigo-db-data:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - big_bear_piwigo_network
    hostname: "{ServiceName}-big-bear-piwigo-db"
networks:
  big_bear_piwigo_network:
    driver: bridge
minVersion: 0.14.0
