# Configuration for pihole-updatelists setup

# Name of the big-bear-pihole-updatelists application
name: big-bear-pihole-updatelists
# Service definitions for the big-bear-pihole-updatelists application
services:
  # Service name: big-bear-pihole-updatelists
  # The `big-bear-pihole-updatelists` service definition
  big-bear-pihole-updatelists:
    # Name of the container
    container_name: big-bear-pihole-updatelists
    # Image to be used for the container
    image: jacklul/pihole:2025.08.0
    # Container restart policy
    restart: unless-stopped
    # Environment variables
    environment:
      TZ: "UTC"
      FTLCONF_webserver_api_password: "your_password"
      BLOCKLISTS_URL: "https://v.firebog.net/hosts/lists.php?type=tick"
      REGEX_BLACKLIST_URL: "https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list"
    # Volumes to be mounted to the container
    volumes:
      # Mounting the local /DATA/AppData/big-bear-pihole-updatelists/etc directory to /etc/pihole/ inside the container
      - pihole_updatelists_etc:/etc/pihole/
      # Mounting the local /DATA/AppData/big-bear-pihole-updatelists/etc/pihole-updatelists directory to /etc/pihole-updatelists/ inside the container
      - pihole_updatelists_etc_pihole_updatelists:/etc/pihole-updatelists/
      # Mounting the local /DATA/AppData/big-bear-pihole-updatelists/dnsmasq.d directory to /etc/dnsmasq.d inside the container
      - pihole_updatelists_dnsmasq.d:/etc/dnsmasq.d/
    # Ports mapping between host and container
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "10443:443/tcp"
    # Define the networks section
    networks:
      # Define the pihole-network
      - pihole-network
    # Capabilities to be added to the container
    cap_add:
      - NET_ADMIN
# Define the networks section
networks:
  # Define the pihole-network
  pihole-network:
    # Set the driver to bridge
    driver: bridge
volumes:
  pihole_updatelists_etc: {}
  pihole_updatelists_etc_pihole_updatelists: {}
  pihole_updatelists_dnsmasq.d: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: pihole-updatelists
    description: Pi-hole® Updatelists
    useHost: true
    target: http://localhost:8080
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
