cosmos-installer: null
services:
  app:
    image: jgraph/drawio:31.5.3@sha256:03df6174f15aaad2df7f8465720860e3930a658a8790bdb0d131606dc6acb32a
    container_name: drawio
    ports:
      - "8080:8080"
    restart: unless-stopped
minVersion: 0.14.0
