cosmos-installer: null
services:
  app:
    image: jgraph/drawio:31.4.6@sha256:139b43305b77c46575d5af5dcc7b6c38dc7ea22f430fdfe954fb8f96926643e5
    container_name: drawio
    ports:
      - "8080:8080"
    restart: unless-stopped
minVersion: 0.14.0
