# Configuration for jellystat setup

# Name of the big-bear-jellystat application
name: big-bear-jellystat
# Service definitions for the big-bear-jellystat application
services:
  # Service name: big-bear-jellystat
  # The `big-bear-jellystat` service definition
  big-bear-jellystat:
    # Name of the container
    container_name: big-bear-jellystat
    # Image to be used for the container
    image: cyfershepard/jellystat:1.1.6
    # Container restart policy
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8a23ad09-61cf-4178-a783-6d4586496e3a
      - POSTGRES_IP=big-bear-jellystat-db
      - POSTGRES_PORT=5432
      - JWT_SECRET="my-secret-jwt-key"
    # Volumes to be mounted to the container
    volumes:
      - jellystat_backup_data:/app/backend/backup-data
    # Ports mapping between host and container
    ports:
      # Mapping port 3000 of the host to port 3000 of the container
      - "3000:3000"
    networks:
      - big-bear-jellystat-network
  big-bear-jellystat-db:
    container_name: big-bear-jellystat-db
    image: postgres:15.2
    environment:
      POSTGRES_DB: "jfstat"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8a23ad09-61cf-4178-a783-6d4586496e3a
    volumes:
      - jellystat_postgres_data:/var/lib/postgresql/data # Mounting the volume
    networks:
      - big-bear-jellystat-network
networks:
  big-bear-jellystat-network:
    name: big-bear-jellystat-network
    driver: bridge
volumes:
  jellystat_backup_data: {}
  jellystat_postgres_data: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: jellystat
    description: Jellystat
    useHost: true
    target: http://localhost:3000
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
