cosmos-installer: null
name: big-bear-nextcloud
services:
  "{ServiceName}-nextcloud":
    container_name: "{ServiceName}-nextcloud"
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.4
    restart: unless-stopped
    ports:
      - 7580:80
    volumes:
      - "{ServiceName}-nextcloud-data:/var/www/html"
    environment:
      - POSTGRES_HOST={ServiceName}-db-nextcloud
      - REDIS_HOST={ServiceName}-redis-nextcloud
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_ADMIN_USER=casaos
      - NEXTCLOUD_ADMIN_PASSWORD=casaos
      - TRUSTED_PROXIES=
      - OVERWRITEPROTOCOL=http
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
    depends_on:
      - "{ServiceName}-db-nextcloud"
      - "{ServiceName}-redis-nextcloud"
    networks:
      - nextcloud_network
    hostname: "{ServiceName}-nextcloud"
  "{ServiceName}-db-nextcloud":
    container_name: "{ServiceName}-db-nextcloud"
    image: postgres:14.2
    restart: unless-stopped
    volumes:
      - "{ServiceName}-db-nextcloud-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - POSTGRES_DB=nextcloud
    networks:
      - nextcloud_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U casaos -d nextcloud
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: "{ServiceName}-db-nextcloud"
  "{ServiceName}-redis-nextcloud":
    container_name: "{ServiceName}-redis-nextcloud"
    user: 1000:1000
    image: redis:6.2.6
    restart: on-failure
    volumes:
      - "{ServiceName}-redis-nextcloud-data:/data"
    networks:
      - nextcloud_network
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: "{ServiceName}-redis-nextcloud"
  "{ServiceName}-cron":
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.4
    restart: on-failure
    volumes:
      - "{ServiceName}-cron-data:/var/www/html"
    entrypoint: /cron.sh
    depends_on:
      - "{ServiceName}-db-nextcloud"
      - "{ServiceName}-redis-nextcloud"
    networks:
      - nextcloud_network
    container_name: "{ServiceName}-cron"
    hostname: "{ServiceName}-cron"
networks:
  nextcloud_network:
    driver: bridge
minVersion: 0.14.0
