name: Sync with big-bear-casaos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  update-check:
    env:
      MERGE_METHOD: "squash"
      MERGE_DELETE_BRANCH: "true"
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4.1.0
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Run script
        run: sh build.sh

      # Assuming there are steps here to commit changes
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Sync with big-bear-casaos"
          title: "Sync with big-bear-casaos"
          body: "Ran the sync script to update the repository with the latest changes from big-bear-casaos."
          branch: "sync-with-big-bear-casaos" # This should be the branch with new changes
          labels: "automerge"
