cosmos-installer: null
name: big-bear-seafile
services:
  "{ServiceName}-big-bear-seafile":
    container_name: "{ServiceName}-big-bear-seafile"
    image: seafileltd/seafile-mc:12.0.4
    restart: unless-stopped
    volumes:
      - "{ServiceName}-big-bear-seafile-data:/shared"
    ports:
      - 8080:80
    environment:
      - DB_HOST={ServiceName}-big-bear-seafile-db
      - DB_ROOT_PASSWD=seafilepassword
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=admin@example.com
      - SEAFILE_ADMIN_PASSWORD=asecret
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=docs.seafile.com
    networks:
      - big_bear_seafile_network
    hostname: "{ServiceName}-big-bear-seafile"
  "{ServiceName}-big-bear-seafile-db":
    image: mariadb:10.11
    container_name: "{ServiceName}-big-bear-seafile-db"
    environment:
      - MYSQL_ROOT_PASSWORD=seafilepassword
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - "{ServiceName}-big-bear-seafile-db-data:/var/lib/mysql"
    restart: unless-stopped
    networks:
      - big_bear_seafile_network
    hostname: "{ServiceName}-big-bear-seafile-db"
  "{ServiceName}-big-bear-seafile-memcached":
    container_name: "{ServiceName}-big-bear-seafile-memcached"
    image: memcached:1.6.32
    entrypoint: memcached -m 256
    networks:
      - big_bear_seafile_network
    hostname: "{ServiceName}-big-bear-seafile-memcached"
networks:
  big_bear_seafile_network:
    driver: bridge
minVersion: 0.14.0
