cosmos-installer: null
services:
  app:
    image: linuxserver/shotcut:26.9.27@sha256:7cbfc1a31a0b6a302978bf4b8c5c55f602ac4ec130caa4b82479ccdf59517d14
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/shotcut/config
        target: /config
minVersion: 0.14.0
