cosmos-installer: null
services:
  app:
    image: linuxserver/gitqlient:1.6.3@sha256:69d602cdd9e90633f27ecd8fccad908996983ee305ff2e511fd502a3d625c0f7
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/gitqlient/config
        target: /config
minVersion: 0.14.0
