name: big-bear-jellyseerr # Name of the compose project
services:
  app:
    image: fallenbagel/jellyseerr:2.7.3 # Image to use for the jellyseerr service
    ports:
      - "5055:5055" # Maps port 5055 on the host to port 5055 on the container
    volumes:
      - jellyseerr_config:/app/config # Binds a volume from host to container for configuration
    environment:
      - LOG_LEVEL=debug # Sets the log level to debug
      - TZ=$TZ # Sets the timezone, using host's timezone variable
    restart: unless-stopped # Service will restart unless it is explicitly stopped
    network_mode: bridge # Uses bridge network mode
volumes:
  jellyseerr_config: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: jellyseerr
    description: Jellyseerr
    useHost: true
    target: http://localhost:5055
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
