# Configuration for playit-docker-web setup

# Name of the big-bear-playit-docker-web application
name: big-bear-playit-docker-web
# Service definitions for the big-bear-playit-docker-web application
services:
  # Service name: big-bear-playit-docker-web
  # The `big-bear-playit-docker-web` service definition
  big-bear-playit-docker-web:
    # Name of the container
    container_name: big-bear-playit-docker-web
    # Image to be used for the container
    image: wisdomsky/playit-docker-web:1.1
    # Container restart policy
    restart: unless-stopped
    # Network mode
    network_mode: host
    # Environment variables for the container
    environment:
      - WEBUI_PORT=8008
    # Volumes to be mounted to the container
    volumes:
      - playit_docker_web_config:/config
volumes:
  playit_docker_web_config: {}

# Cosmos-specific routes for reverse proxy
routes:
  - name: playit-docker-web
    description: Playit Docker Web
    useHost: true
    target: http://localhost:8008
    mode: SERVAPP
    Timeout: 14400000
    ThrottlePerMinute: 0
    BlockCommonBots: false
    BlockAPIAbuse: false
