cosmos-installer: null
name: big-bear-playit-docker-web
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: wisdomsky/playit-docker-web:1.1
    restart: unless-stopped
    network_mode: host
    environment:
      - WEBUI_PORT=8008
    volumes:
      - "{ServiceName}-data:/config"
    hostname: "{ServiceName}"
minVersion: 0.14.0
